### ISSUE TITLE
maxRows configuration is not being respected

### ISSUE THREAD

**Issue by fubz** [strongloop/loopback-connector-oracle#101]
I recently encountered an issue with my unfiltered api calls being limited to 100 records.  

I set debug using DEBUG=loopback:connector:* 
This showed me that my oracle connector has a property:  "maxRows": 100

in my server/datasources.json, I set the maxRows property to 1000; however, my unfiltered api calls are still  only returning 100 rows.

What am I missing?

**Comment by raymondfeng** [comment]
I assume you see the problem with loopback-connector-oracle@3.x. There is a bug that we don't set the properties onto the oracle driver.

**Comment by raymondfeng** [comment]
We do support maxRows. See https://github.com/strongloop/loopback-connector-oracle/blob/master/lib/oracle.js#L44. What do you see `Settings` from https://github.com/strongloop/loopback-connector-oracle/blob/master/lib/oracle.js#L105?

**Comment by fubz** [comment]
I set the server/datasource.json file to have the following parameters:

````"sts_api": {
    "host": "${API_HOST}",
    "port": "${API_PORT}",
    "database": "${API_DATABASE}",
    "password": "${API_PASSWORD}",
    "name": "api",
    "user": "API",
    "connector": "oracle",
    "maxRows": 1000,
    "debug": true
  }
````
I do not see anything being printed to the console; however when I set the environment variable DEBUG=loopback:connector:*
I see the following dumped to the console

````
  loopback:connector:oracle Settings: {"connectString":"//scan-host.domain.com:1521/DB.domain.com","user":"API","password":"*******","debug":true,"poolMin":1,"poolMax":10,"poolIncrement":1,"poolTimeout":60,"isAutoCommit":true,"outFormat":4002,"maxRows":1000,"stmtCacheSize":30,"connectionClass":"loopback-connector-oracle"} +0ms
  loopback:connector:oracle Connecting to //scan-host.domain.com:1521/DB.domain.com +2ms
  loopback:connector:oracle Connected to //scan-host.domain.com:1521/DB.domain.com +179ms

````

**Comment by raymondfeng** [comment]
From the debug printout, your setting of `maxRow` is honored by LoopBack ("maxRows":1000). We pass the settings to oracledb.createPool(). 

Please note `oracledb` allow driver-level settings which can be overridden by pool level. 
See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#oracledbproperties.

**Comment by fubz** [comment]
Even though loopback says that it will pull a max of 1000 rows, I have a table that has 141 total rows in it, and calling an unfiltered, non-limited, non-scoped model (/api/myTable) results in only 100 records being pulled in.

Is there a way to create a properties file in order to set the driver-level settings?

I feel like I'm missing something obvious.  I even went ahead and created a new very simple model.  Populated my table with 1000 rows of data.
My basic GET using the loopback API returned only 100 rows.

my model:
````
{
  "name": "fileList",
  "options": {
    "idInjection": false,
    "oracle": {
      "schema": "API_SCHEMA",
      "table": "MY_FILE_LIST"
    }
  },
  "properties": {
    "id": {
      "type": "String",
      "required": true,
      "length": 255,
      "precision": null,
      "scale": null,
      "oracle": {
        "columnName": "ID",
        "dataType": "VARCHAR2",
        "dataLength": 255,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "N"
      }
    },
    "directory": {
      "type": "String",
      "required": false,
      "length": 255,
      "precision": null,
      "scale": null,
      "oracle": {
        "columnName": "DIRECTORY",
        "dataType": "VARCHAR2",
        "dataLength": 255,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "Y"
      }
    }
  }
}
````

**Comment by raymondfeng** [comment]
Can you do a quick test by calling the following code?
```js
var oracledb = require('oracledb');
oracledb.maxRows = 1000;
```
Maybe `maxRows` cannot be set at pool creation level.

**Comment by fubz** [comment]
Alright, I made a temp project:

````
var oracledb = require('oracledb');
oracledb.maxRows = 1000;
console.log(JSON.stringify(oracledb))
````
/WebstormProjects/test $ node index.js 
{"poolPingInterval":60,"oracleClientVersion":1201000200,"lobPrefetchSize":16384,"fetchAsString":[],"externalAuth":false,"connectionClass":"","version":11202,"outFormat":4001,"maxRows":1000,"extendedMetaData":false,"autoCommit":false,"prefetchRows":100,"stmtCacheSize":30,"poolTimeout":60,"poolIncrement":1,"poolMin":0,"poolMax":4,"DEFAULT":0,"DB_TYPE_VARCHAR":1,"DB_TYPE_NUMBER":2,"DB_TYPE_DATE":12,"DB_TYPE_RAW":23,"DB_TYPE_CHAR":96,"DB_TYPE_BINARY_FLOAT":100,"DB_TYPE_BINARY_DOUBLE":101,"DB_TYPE_ROWID":104,"DB_TYPE_CLOB":112,"DB_TYPE_BLOB":113,"DB_TYPE_TIMESTAMP":187,"DB_TYPE_TIMESTAMP_TZ":188,"DB_TYPE_TIMESTAMP_LTZ":232,"STRING":2001,"NUMBER":2002,"DATE":2003,"CURSOR":2004,"BUFFER":2005,"CLOB":2006,"BLOB":2007,"BIND_IN":3001,"BIND_INOUT":3002,"BIND_OUT":3003,"ARRAY":4001,"OBJECT":4002,"queueRequests":true,"queueTimeout":60000}

**Comment by raymondfeng** [comment]
Does it help you go beyond 100 rows?

**Comment by fubz** [comment]
Nope, still stuck at 100 rows

**Comment by raymondfeng** [comment]
Hmm, then it might be an issue with `oracledb`. Is it possible to come up a very simple test to use `oracledb` directly (execute a SELECT statement directly) that can be used to reproduce the problem?

**Comment by cjbj** [comment]
For reference,`maxRows` can be set at the global level or at execution.  It can't be set on a pool or connection (this has been [requested](https://github.com/oracle/node-oracledb/issues/361))

**Comment by raymondfeng** [comment]
@fubz For the short term, I guess we need to keep such options and merge them at `execute` level.

**Comment by raymondfeng** [comment]
First attempt to fix the issue - https://github.com/strongloop/loopback-connector-oracle/commit/2fffcba9fb4b51b90b78fdba7cad8eb51772c458

**Comment by fubz** [comment]
I have not been able to write up some test code to try a select statement; however, this morning I had a finding.  

One of the VMs that was running my loopback API restarted, it is no longer having the maxRows of 100 issue.  I currently do not have a table that has more than 1000 records to ensure my configured maxRows of 1000 is being followed, but I can investigate that later.

Let's take a step back in my issue.  This issue occurred after I recreated my loopback API from scratch and deployed it to my servers as a new project.  Thus an entirely fresh install, including the oracle drivers that get installed during the loopback install.  I do not know enough about the lower level implementation details to conclude on what may have gone wrong after the second install.

Back to today, I have 1 VM with the issue, that will most likely be resolved when I restart it.
Then a second VM that no longer has the issue, since it rebooted.

Knowing this information, does this change where to look where the issue could be?  Does this have anything to do with cjbj's comment (the global level?).  Again, I do not know enough about the lower level implementation details to draw conclusions or proceed on my own.

Thanks!
