### ISSUE TITLE
Query metadata support

### ISSUE THREAD

**Issue by sonia1588** [strongloop/loopback-connector-oracle#125]
Is any interface available with oracle connector to return column metadata if SQL query is given as input?

**Comment by raymondfeng** [comment]
Do you want to do so for generated SQL statements for CRUD operations on a model or native SQL on your own? You can access `dataSource.connector.executeSQL()`.

**Comment by sonia1588** [comment]
I need for Native SQL on my own.  
There are interface available in LoopBack to execute native SQL using existing model. https://loopback.io/doc/en/lb3/Executing-native-SQL.html 

Is it possible to generate model out of native SQL?

**Comment by cjbj** [comment]
FWIW, node-oracledb 2.2 introduced a [getStatementInfo()](https://oracle.github.io/node-oracledb/doc/api.html#getstmtinfo) method.
