### ISSUE TITLE
Connecting to database using TLS

### ISSUE THREAD

**Issue by harshu108** [strongloop/loopback-connector-oracle#131]
# Description/Steps to reproduce
Can I connect to Oracle databse secured using TLS?

# Expected result

# Additional information
If I have a cloud hosted public database secured with TLS, can I still use this connector?
I don't see any provision to add TLS certificates to the datasource.

**Comment by raymondfeng** [comment]
The SSL/TLS connection to oracle DB is configured at the instant client level. See https://github.com/oracle/node-oracledb/issues/517 and https://github.com/oracle/node-oracledb/issues/411 for more information.

**Comment by cjbj** [comment]
There's a bit of doc about securing network traffic in https://github.com/oracle/node-oracledb/blob/master/doc/api.md#securenetwork This covers Oracle's native network encryption. There is a cross reference to the generic Oracle doc for SSL, since SSL setup is more involved.
