### ISSUE TITLE
Windows: repeated install screws up PATH

### ISSUE THREAD

**Issue by piscisaureus** [strongloop/loopback-connector-oracle#14]
Installing the connector prepends an entry to my PATH every time.
At some point the path becomes too long and old entries start dropping off.
I think it's not needed to modify the path at all - but at least don't add the same location many times?

To show off some of my histrionic personality disorder, I've pasted below an excerpt of - what I just discovered to be - my user %PATH%:

D:\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;D:\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\a\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;D:\a\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\test\node_modules\slc\node_modules\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;D:\sls-sample-app\node_modules\loopback-connector-oracle\node_modules\instantclient;

**Comment by ebickle** [comment]
@raymondfeng Is this still an issue with v3.0.0 or is this issue obsolete? We abandoned the current 2.x branch because of this bug and are building against v3.0 and haven't seen the issue. Entirely different oracle driver now.

**Comment by dhmlau** [comment]
@piscisaureus , according to @ebickle, it looks like this problem has been fixed in v3.0.  Is it good to close?  Thanks.

**Comment by dhmlau** [comment]
Due to inactivity, closing this issue.  @piscisaureus, feel free to reopen if the issue still exists.  Thanks.
