### ISSUE TITLE
LoopBack Discover-Schema Created Incorrect Type

### ISSUE THREAD

**Issue by telkomops** [strongloop/loopback-connector-oracle#144]
node bin\discover-schema.js to oracle generates the property type incorrectly.
Oracle 11g R2 , Table has schema with CLOB.
As per lb3 documentation CLOB should be mapped to buffer object.
discover-schema.js maps the CLOB to binary which is not recognized by Swagger.

**Comment by jannyHou** [comment]
@telkomops Could you follow the template in https://github.com/strongloop/loopback-connector-oracle/issues/new and provide us a sandbox to reproduce the problem? Thanks.

**Comment by ge-gao** [comment]
with `lb4 discover` I got the same issue. After the model of an Oracle table gets generated, the CLOB type column is set to type `Binary`. 

```ts
  @property({
    type: '**Binary**',
    length: 4000,
    oracle: {columnName: 'IMPRINT', dataType: '**CLOB**', dataLength: 4000, dataPrecision: null, dataScale: null, nullable: 'Y'},
  })
  imprint?: **Binary**;
```
This is shown as validation error: 

```
Cannot find name 'Binary'.ts(2304)
Public property 'imprint' of exported class has or is using private name 'Binary'.ts(4031)
```

**Comment by bajtos** [comment]
Support for `Binary` type in LB4 is discussed in https://github.com/strongloop/loopback-next/issues/6295 and https://github.com/strongloop/loopback-next/pull/6476
