### ISSUE TITLE
Support for Node v8?

### ISSUE THREAD

**Issue by fubz** [strongloop/loopback-connector-oracle#152]
Will this project ever support Node v8, or is there an alternative?

**Comment by joostdebruijn** [comment]
I use it on Node 8 and 9 without any problems. Which problems do you encounter?

**Comment by fubz** [comment]
During the setup process, there is a step that downloads pre-compiled binaries that vary depending on the node version.  When I install using node8, there binaries are not there and the install fails.

**Comment by joostdebruijn** [comment]
Ah, I worked around that by explicitly installing node-oracledb as dependency in my own project (remember that you'll have to install the 1.x version of node-oracledb). The loopback-oracle-installer will detect that install and goes ahead.

However, I hope #149 will get merged soon, as that will resolve this issue.

**Comment by fubz** [comment]
I finally got a chance to try out your suggestion.  I was able to get my loopback-connector-oracle install with node v8, (currently in my development environment which is Windows 7 unfortuantly).

A couple of notes, these are incomplete, but many of the issues I encountered are well documented around the oracledb github.

First, remove node_modules from the project.  It really makes the install easier and with less conflicts.
Then, npm install oracledb@^1
then, npm install loopback-connector-oracle@^3  (I previously had 2, that would not work)
then a final npm install to finish the rest of the project dependencies.
And finish with a npm rebuild to get rid of the old binaries that were build for node v6 that was previously on my system.

In the middle of that there was some dependency hell and pre-reqs that caused a couple hours worth of reading through documentation for oracledb.  But relative to other Oracle documentation, it was well documented and proceeded forward smoothly.

**Comment by fubz** [comment]
Restarted my computer today and received: `
[project_path]\node_modules\oracledb\build\Release\oracledb.node is not a valid Win32 application.
`
*sigh* time to figure out where the heck a 32 bit library came from

**Comment by cjbj** [comment]
@fubz check the common thing first: does PATH contain the correct version of the Oracle libraries?

**Comment by fubz** [comment]
My PATH was a problem.  This issue prompted me to reformat my development PC, it was needed and it allowed me to better setup my environment.  I really hope we see PR 149 sometime soon.  Having to deal with oracledb v1.x is a configuration nightmare.  
Thanks everyone for your efforts, your efforts do not go unnoticed.
