### ISSUE TITLE
ORA-00942: table or view does not exist errorNum: 942, offset: 92

### ISSUE THREAD

**Issue by metallica666** [strongloop/loopback-connector-oracle#154]
I have seen this question in several post of internet an i try everithing to solve the problem. I verify if the table exist with plsql developer, check if I have SELECT permission for v_session. The table exist and belong's to the user. Inclusive i insert in to a table with a script for the initial data, but loopback functions always return that error. I reinstall the oracle, I don't know what else to do. Please help

**Comment by dhmlau** [comment]
@metallica666 , if you have tried to access the database using the same credentials set in the datasources.json, would it be because different schema names being used when connecting manually vs connecting using LoopBack?

**Comment by metallica666** [comment]
Thanks for response @dhmlau , I solve the problem. The table ACL it wasn't create, so . I create the table with the script and all work perfectly

**Comment by Mahm7oud** [comment]
@metalgabe I facing same issue can you please let me know how can I solve it.  

Thanks

**Comment by gabe2code** [comment]
@Mahm7oud Did you try to see if all the tables are properly created?

**Comment by Mahm7oud** [comment]
@gabe2code thank you for your interest, the table was created already .

**Comment by gabe2code** [comment]
@Mahm7oud can you please share some demo?, for me that was the key for solve the issue
