### ISSUE TITLE
NJS-054: Binary build/Release/oracledb.node was not installed

### ISSUE THREAD

**Issue by bssiva** [strongloop/loopback-connector-oracle#156]
Hi All,

I understand that this particular issue is spoken wide, however, I'm facing this issue still.  Below is the my system configuration with installed softwares:
 OS : Windows 7 Enterprise 64 bit.
NPM: 5.6.0
Node: 8.11.3
Python:2.7.2
Oracle Client: instantclient_12_2
MS Visual Studio : 2017.

I have set my proxy as I'm behind the firewall. Every time I tried to install the oracle connector I always get the below error.

C:\app\lbproject\test>npm install loopback-connector-oracle --save

> oracledb@2.3.0 install C:\app\lbproject\epm-market\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.3.0-node-v57-win32-x64.gz
oracledb ERR! connect ETIMEDOUT XXX.XXX.XXX.XXX:443
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can anyone kindly help me pls to resolve this issue

Regards,
Siva.

**Comment by raymondfeng** [comment]
Can you try to run `npm i oracledb@2.3.0` to see if it works? 

It seems that you have trouble connecting to `192.30.255.112:443`. Is it your https proxy?

**Comment by cjbj** [comment]
Remember you currently need to set the proxy via environment variables, not via `npm config`.  This may [change](https://github.com/oracle/node-oracledb/pull/919).

**Comment by bssiva** [comment]
Thanks much for the suggestion. I was able to install after coming out of my proxy servers. Thanks
