### ISSUE TITLE
New release with 3.x driver?

### ISSUE THREAD

**Issue by joostdebruijn** [strongloop/loopback-connector-oracle#170]
Recently in PR #167 the Oracle driver is upgraded to 3.x. That will also enable support for Node 11.x. The current version doesn't support Node 11.x. Can someone trigger a new release of the module?

**Comment by cjbj** [comment]
The 'current' version works fine with Node.js 11. There were just no pre-built binaries for Node.js 11 prior to node-oracledb 3.0.1

**Comment by joostdebruijn** [comment]
Version 4.1.1 (the latest release) of this module installs node-oracledb 2.3.0. It doesn't fallback to a build after the download of prebuild binaries fails. The PR with node-oracledb > 3.x is already accepted, so a new release will solve that.

**Comment by dhmlau** [comment]
Thanks for the reminder @joostdebruijn. `loopback-connector-oracle@4.1.2` is released. 
I'd like to close this issue as resolved.  Thanks.
