### ISSUE TITLE
Insert into BLOB field fails

### ISSUE THREAD

**Issue by marktreble** [strongloop/loopback-connector-oracle#172]
# Description/Steps to reproduce
Attempt to insert binary data into a BLOB column fails with 'Invalid Hex Value'
{
"USER_DEVICE_ID":20,
"SESSION_ID":"jQKCwhrnQgCGPqFn-LYwMiWWGTDBvnQi",
"SESSION_DATA":{"type":"Buffer","data":[97,98,99]},
"CREATED_DATE":"Mon Dec 10 2018 08:26:57",
"EXPIRY_DATE":"Mon Dec 10 2018 08:56:57"
}

# Result
Fails with unexpected HEX Value

# Additional information
I have fixed this on my local copy by modifying the code in oracle.js:

```
Oracle.prototype.toColumnValue = function(prop, val) {
    if (prop.type === Buffer) {
      return val;
    }

  .....

}
```

I found this code in the MySQL connector - which works!
Without this handler, the value gets serialized and therefore fails the insert.

Please add! Thanks.

**Comment by dhmlau** [comment]
@marktreble , since you have fixed this issue locally, are you interested in submitting a PR?  And please add tests too. :)  Thanks!
