### ISSUE TITLE
Feature request: Add support for connection URL

### ISSUE THREAD

**Issue by bmaupin** [strongloop/loopback-connector-oracle#174]
Most of the other database connectors support a `url` parameter, so we can use a connection URL instead of having to specify each property separately. For example:

> url | String | Use instead of thehost,port,user,password, anddatabaseproperties. For example:'postgres://test:mypassword@localhost:5432/dev'.

https://loopback.io/doc/en/lb3/PostgreSQL-connector.html#properties

> url | String | Connection URL of form mysql://user:password@host/db. Overrides other connection settings.

https://loopback.io/doc/en/lb3/MySQL-connector.html#properties

> url | String |   | Use instead of the host, port, user, password, and database properties. For example: 'mssql://test:mypassword@localhost:1433/dev'.

https://loopback.io/doc/en/lb3/SQL-Server-connector.html#connector-settings

> url | String | Connection URL of form mongodb://user:password@host/db. Overrides other connection settings (see below).

https://loopback.io/doc/en/lb3/MongoDB-connector.html#connection-properties

If I understand correctly, it looks like [`connectString` supports hostname, port, and database](https://github.com/strongloop/loopback-connector-oracle/blob/8c2a8f9b7f20a31e3bff77a31f0ccf3caae31051/lib/oracle.js#L77:L83), but it'd be nice if a syntax similar to the other databases was supported that included username and password as well.

Thanks!

**Comment by raymondfeng** [comment]
@bmaupin I believe that we support `url` already. See https://github.com/strongloop/loopback-connector-oracle/blob/master/lib/oracle.js#L58

**Comment by bmaupin** [comment]
@raymondfeng From the link you sent, it looks like `url` is just an alias for `tns` or `connectString`.

So if you look here:

https://github.com/strongloop/loopback-connector-oracle/blob/master/lib/oracle.js#L81:L82

You can see this format is what's currently supported:

`//host:port/db`

But that still requires username/password to be specified separately. What I'm asking for is something similar to what the other databases support, e.g.:

`oracle://user:password@host:port/db`

Of course it's just a convenience feature, but it would also bring this connector in line with the others in terms of a consistent user experience.

Thanks!
