### ISSUE TITLE
Oracle DB security support

### ISSUE THREAD

**Issue by devatiwa** [strongloop/loopback-connector-oracle#175]
- Does oracle loopback connector provides support for Oracle 12c security features 
   - Data security over the network

**Comment by raymondfeng** [comment]
@devatiwa We use https://github.com/oracle/node-oracledb as the driver. It seems to support Oracle 12c. See https://oracle.github.io/node-oracledb/doc/api.html.

@cjbj, can you confirm?

**Comment by cjbj** [comment]
See https://oracle.github.io/node-oracledb/doc/api.html#securenetwork  I don't recall this requiring 12c but maybe in some earlier version there was a differently licensed option.

**Comment by dhmlau** [comment]
Closing this issue as answered.
