### ISSUE TITLE
Loopback 3 error "errornum": 942, "offset": 92,

### ISSUE THREAD

**Issue by Mahm7oud** [strongloop/loopback-connector-oracle#177]
Hi ; 
I need help please , i am getting below error when i am trying to test API . i am using loopback3 and oracle database .
Error 
"errornum": 942, "offset": 92, 
Ora table or view doesn't exist.

**Comment by dhmlau** [comment]
@Mahm7oud, the first thing to check would be to see if the table/view does exist.
If that exists, you can check the `model-config.json`, whether the APIs you're testing go to the datasource that you're thinking.

**Comment by dhmlau** [comment]
@Mahm7oud, we believe we've answered your question, so I'm closing this issue now.  If you're still running into connection issues, please open a new ticket. Thanks.
