### ISSUE TITLE
Fix CI Failures

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-connector-oracle#183]
# Description/Steps to reproduce
Currently there are five CI failures:

```
   1) juggler-v3
        datatypes
          "before all" hook for "should resolve top-level "type" property correctly":
      Error: ORA-00972: identifier is too long
   
 
   2) juggler-v3
        basic-querying
          "before all" hook in "basic-querying":
      Error: ORA-00955: name is already used by an existing object
   
 
   3) juggler-v3
        regexp operator
          "before all" hook: seed for "should return an error for invalid data types":
      Error: ORA-01400: cannot insert NULL into ("TEST"."USER"."ID")
   
 
   4) juggler-v4
        datatypes
          "before all" hook for "should resolve top-level "type" property correctly":
      Error: ORA-00972: identifier is too long
   
 
   5) juggler-v4
        basic-querying
          "before all" hook in "basic-querying":
      Error: ORA-00972: identifier is too long
   
```

The `ORA-00972: identifier is too long` error happens when an identifier is over 30 characters.

The failures are from the `before` hooks of the [datatype.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/datatype.test.js) and [basic-querying.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js) files (not sure where `regexp operator` is from).

# Acceptance Criteria
- [ ] Fix the errors so CI passes

**Comment by cjbj** [comment]
As of Oracle DB 12.2 identifiers can be 128 characters. Do you need to test older DBs?  Oracle 18 & 19 are also available - and there is a [free Oracle XE 18](https://www.oracle.com/technetwork/database/database-technologies/express-edition/downloads/index.html) available.

**Comment by agnes512** [comment]
Maybe check db versions and update Docker images. 
and check sql statement in [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/datatype.test.js#L20) and use debug string.

**Comment by hacksparrow** [comment]
CI made to pass via PR: https://github.com/strongloop/loopback-connector-oracle/pull/189.
Follow up issue: https://github.com/strongloop/loopback-connector-oracle/issues/190.
