### ISSUE TITLE
node-oracledb 4.0 is avaialble

### ISSUE THREAD

**Issue by cjbj** [strongloop/loopback-connector-oracle#184]
I released node-oracledb 4.0 a few hours ago.  The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40

It requires Node.js 8.16+, 10.16+ or 12.  We refactored to use [N-API](https://nodejs.org/api/n-api.html) but this has a nasty performance issue only fixed in the 8.16 & 10.16 (and 12) releases.  Using N-API does mean that any node-oracledb installation shouldn't need upgrading when future Node.js versions are used.

**Comment by dhmlau** [comment]
Related to PR https://github.com/strongloop/loopback-connector-oracle/pull/186

**Comment by dhmlau** [comment]
Closing as resolved via PR https://github.com/strongloop/loopback-connector-oracle/pull/186. Thanks @cjbj for pointing this out.
