### ISSUE TITLE
New release with 4.0 driver?

### ISSUE THREAD

**Issue by joostdebruijn** [strongloop/loopback-connector-oracle#191]
Are there any plans to create a new release soon with the oracledb 4.0 driver? The change is already merged for some months on the master branch. This will enable us to use Node 12.x.

**Comment by dhmlau** [comment]
@joostdebruijn, coincidently I was thinking to publish releases for this module and other connectors today!  Will let you know when it's done.

**Comment by dhmlau** [comment]
Released `loopback-connector-oracle@4.4.0`.  Thanks for your reminder @joostdebruijn!
