### ISSUE TITLE
oracledb dependency

### ISSUE THREAD

**Issue by ataft** [strongloop/loopback-connector-oracle#194]
The oracledb dependency was recently set to `"oracledb": "^4.0.0"` which has fairly strict NodeJS version requirements (10.16+). However, it doesn't appear that anything in the loopback-connector-oracle module requires this. Would it make sense for the package.json entry to be `"oracledb": ">=3.1.2"`?

**Comment by dhmlau** [comment]
@ataft, which version of Node.js are you on? Please note that Node.js 8 will be EOL in Dec this  year, so it's recommended that you run your application on Node.js 10+. 

@raymondfeng, do you see issues if we use `"oracledb": ">=3.1.2"`? Thanks.

**Comment by ataft** [comment]
Node 10.15.3. I can't simply upgrade to 10.16 because I'm using a popular binary compiler called zeit/pkg and don't have control over the Node versions. I tried v12.2, but ran into some problems.

**Comment by cjbj** [comment]
> The oracledb dependency was recently set to "oracledb": "^4.0.0" which has fairly strict NodeJS version requirements (10.16+)

For the record, the dependency is 8.16+, 10.16+ or 12+.  This is due to important Node.js N-API memory leak fixes in those releases.  

If all else fails for you, maybe you could hack https://github.com/oracle/node-oracledb/blob/v4.0.1/lib/oracledb.js#L26-L35 to allow it to work with your version - and monitor memory.  I haven't tried this.

**Comment by raymondfeng** [comment]
@cjbj Thank you for clarifying the version requirement.

@ataft Can you stick with loopback-connector-oracle@4.3.0?

**Comment by ataft** [comment]
@raymondfeng No, I need 4.5.0 for my recent CLOB/BLOB [commit](https://github.com/strongloop/loopback-connector-oracle/commit/0202b9a893d8a2844039909deab50f1f46c170d5). For now, I'm using the https://github.com/ataft/loopback-connector-oracle fork, which fixes the oracledb version issue, as well as the https://github.com/strongloop/loopback-connector-oracle/pull/195 PR that fixes table discovery column ordering

I understand the Node fixes and want to upgrade, but cannot for the reasons that I specified. As far as I understand there's absolutely no reason this connector needs oracledb 4.0.0. However, it does mean that a certain number of Loopback customers using Oracle will not be able to use this connector.

**Comment by ataft** [comment]
I was able to upgrade to Node v12.13.1
