### ISSUE TITLE
Node.js application not working with Oracle 19C RAC database

### ISSUE THREAD

**Issue by swejha** [strongloop/loopback-connector-oracle#214]
**Problem Statement –** My Node.js application is working fine with standalone Oracle databases in Dev and UAT environment, however, the same application does not work as expected with RAC database in production environment.

**Steps to reproduce the error**

Start the Node.js application
The connection with Oracle RAC DB is established successfully using Loopback connector oracle
Generally the first API, which fires an insert statement, inserts a record in the db successfully and then goes onto next API, which fires 10-12 select queries.
One of these queries, usually a select from gender table, which fetches 4 records is fired, but it goes in a long wait
The query returns after 13-15 mins with an error (End of Communication error)
The subsequent queries after that get executed successfully
Mostly these steps are reproducible exactly in the same manner with few exceptions in the order in which query will get stuck and go in a long wait

**Diagnosis done this far**

When we trace the sqlnet.ora file on the database, we get to see that the query which was fired at 5:11PM from the application, didn’t reach the database instantly, causing the application go in a hanged state
The query hits the DB at 5:29PM and it executes and result is sent to the application without any delay.

Please let me know if loopback-connector-oracle works fine with ORACLE RAC DB or not.

**Comment by cjbj** [comment]
The question is not so much whether it works with RAC - it obviously connects and works fine for a while. The underlying node-oracledb is extensively tested with RAC.  Are you/Loopback using node-oracledb pooled connections?  Maybe you need to increase UV_THREADPOOL_SIZE?

**Comment by swejha** [comment]
Thanks for your response. The issue was related to port opening on the firewall.
