### ISSUE TITLE
Windows Issues Oracle Connector not available

### ISSUE THREAD

**Issue by codemonkeyneo** [strongloop/loopback-connector-oracle#27]
Having Issues when working with Windows 7.

I keep trying to setup a basic project but cant get the oracle side to work. I have tried using oracle installer, but nothing seems to work on windows ( linux machine I had no problems :) ).

On windows I constantly keep getting that the ' LoopBack connector "oracle" is not installed as any of the following modules:'

----------------------------------------------------------------------------------------------------------------------------
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

events.js:72
        throw er; // Unhandled 'error' event

----------------------------------------------------------------------------------------------------------------------------

So I run the necessary command ;

c:\development\neil-strong-loop\testapp>npm install loopback-connector-oracle
npm WARN package.json testapp@0.0.0 No description
npm WARN package.json testapp@0.0.0 No repository field.
npm WARN package.json testapp@0.0.0 No README data
loopback-connector-oracle@1.4.5 node_modules\loopback-connector-oracle
├── sl-blip@1.0.0
├── loopback-connector@1.2.0
├── async@0.9.0
└── debug@2.0.0 (ms@0.6.2)

Still nothing seems to work but files seems to be in the project directory.

Is there anything else I can try.... ( Ive tried loopback-oracle-installer and I still end up with oracle connector error ).

Cheers

Neil

**Comment by bulldog65** [comment]
codemonkeyneo........I'm having the same issue.  Have you found a solution yet?

**Comment by codemonkeyneo** [comment]
sorry bulldog65 no solution yet, thank god I had a Christmas break but now I will be looking back into this ...

**Comment by codemonkeyneo** [comment]
I've tried updating to the latest version of everything and still have issues.

creating initial project is fine , good old yeoman is there guiding me.... I then try to get the loopback-connector-oracle and end up with a sad face... output as follows.

```
C:\development\myapitest>npm install loopback-connector-oracle

> loopback-oracle-installer@1.3.0 install C:\development\myapitest\node_modules\loopback-connector-oracle\node_modules\loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Windows-x86-1.4.0.tar.gz

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

npm ERR! loopback-oracle-installer@1.3.0 install: `node pkginstall.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@1.3.0 install script.
npm ERR! This is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "loopback-connector-oracle"
npm ERR! cwd C:\development\weatherapiv1
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by codemonkeyneo** [comment]
I have now managed to get this working.

The original oracle error was firstly solved by making sure I was running the 64 bit version of Node.

I then had to update the path variables so it pointed to the instant client vc11 version.

I was then after this getting lots of TNS errors.

The folder that the TNS_ADMIN was pointing at contained another couple of ORA files.

sqlnet.ora and lda.ora. If I removed these files then I can make the connection to the database.

The contents of these files are as follows ;

sqlnet.ora file
```
# SQLNET.ORA Network Configuration File
# Generated by Oracle configuration tools.

#NAMES.DIRECTORY_PATH= (TNSNAMES, LDAP)
NAMES.DIRECTORY_PATH= (TNSNAMES)

ldap.ora
```
ldap.ora file. 

DIRECTORY_SERVERS= (mycompanysdirectoryserver)
DEFAULT_ADMIN_CONTEXT = "mycomanysdccontext"
DIRECTORY_SERVER_TYPE = OID

solution comes out thanks to <a href="https://github.com/alexkb">alexb</a> for getting it working on his machine and being patient while we worked out what differences I had.

It would be nice to understand why sqlnet.ora and ldap.ora are causing the issue , maybe this is a bug ?

**Comment by FatPanther** [comment]
This same error was driving me nuts (Windows 7) - solved it by making sure the PATH entries that are created during the loopback connector install come before any other oracle-related entries - you may need to adjust not only the user PATH but system PATH as well.

**Comment by sgarggit** [comment]
Hi,
I am also facing the same issue with loopback-connector-oracle, when I cam across this thread on the same error. Can you please elaborate on how did you resolve this problem. My env. is 64 bit and I am using the node.js version 0.10.35. I have also tried setting the PATH env. variable to point to ..../instantclient/vc11, still getting the same error

WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

./connectors/oracle
 loopback-connector-oracle

To fix, run:
npm install loopback-connector-oracle


events.js:72
 throw er; // Unhandled 'error' event

Please help me in this regard.

**Comment by codemonkeyneo** [comment]
sgarggit are you using the 64-bit version of Node ?

**Comment by sgarggit** [comment]
yes neo, I am using the 64 bit version of node. node version is v0.10.35

Thanks

**Comment by codemonkeyneo** [comment]
mmmmmm Its been a while, ended up using a different framework in the end but it was nice to get this working :).

I noticed I tried the SLC ARC steps a few post up .... then I called

npm install loopback-connector-oracle --save

What happens if you run through installing ARC and then running above npm install.... output your results step by step and Ill see if I can help or anything comes back to me.

**Comment by sgarggit** [comment]
sure , I will try with slc arc.

**Comment by Tomkinen** [comment]
I have exactly the same issue here with Windows Server 2012.
Node version:
10.38 (64 bit)

In path i have the "\node_modules\instantclient\vc11" -folder and by looking at the content of the folders created i can see that the files are there. Still the end result when trying to "slc run" with having "oracle" as datasource i end up in same situation as was presented in the first message of this issue:
 "WARNING: LoopBack connector "oracle" is not installed as any of the following modules."

I have installed visual studio express 2013 for desktop.

I can run "slc run" successfully if there is no "oracle" listed in the datasources.json. I have installed node and loopback with oracle drivers earlier in OS X with no issues. With windows adding oracle db support to loopback seems to be causing issues not only for me, but others as well. I received no error messages when i ran "npm install loopback-connector-oracle --save", so troubleshooting this is impossible for me. Can you help me?

**Comment by eholzwarth** [comment]
I have this issue with RHEL 7 Node 4.4.2. Tried everything. No error messages beyond the ```WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle```
