### ISSUE TITLE
Installation process: putting strong-oracle.rc in $HOME is a bad idea

### ISSUE THREAD

**Issue by mik01aj** [strongloop/loopback-connector-oracle#29]
Hi, I just installed loopback-connector-oracle and saw the following message:

```
"strong-oracle.rc" has been created in $HOME. Please manually add the
following to your ".bash_profile":

  source /Users/m01/strong-oracle.rc

If you do not use bash as your default shell, please remember to set
$DYLD_LIBRARY_PATH prior to using node:

  export DYLD_LIBRARY_PATH=":/Users/m01/code/lb-loopback-api/node_modules/loopback-connector-oracle/node_modules/instantclient"
```

Shame on you! This is a bad, bad, bad idea. You're cluttering the home folder for all the developers, plus you suggest to add a project-specific location to a global config, which will beak other projects when I remove this one and will make me angry when I want different projects use different versions of this library. Please don't do this.

**Comment by raymondfeng** [comment]
The environment var is required to activate Oracle Instant Client as the runtime dependency. 

Can you propose a better way?

Here is one way I have in mind:
1. Check the existence of Oracle instant client. If not present, install a copy to $HOME/oracle-instant-client (to be shared)
2. Set up the $HOME/.strong-oracle.rc to contain the DYLD_LIBRARY_PATH

**Comment by mik01aj** [comment]
I suppose you only need this environment variable for some subprocess, so maybe you could set it just for the subprocess only?

And, if it's not relevant, I think it'll be just enough to state that this library requires this environment variable to be set. You could even check it in the module and display an error message if it's not set. Just leave it to the user to set it.

Another idea would be to ask the user to do ``export DYLD_LIBRARY_PATH=":`pwd`/node_modules/loopback-connector-oracle/node_modules/instantclient"`` before he runs the app. (Btw, you could put this info in the error message).

The problem I see is not with the env variable, it's about putting a reference to locallly-installed package into a global context. And don't clutter users' home dirs.
