### ISSUE TITLE
Oracle connector not found even though it is installed - windows server

### ISSUE THREAD

**Issue by Tomkinen** [strongloop/loopback-connector-oracle#37]
I have exactly the same issue here as issue #27  with Windows Server 2012.
Node version:
10.38 (64 bit)

In path i have the "\node_modules\instantclient\vc11" -folder and by looking at the content of the folders created i can see that the files are there. Still the end result when trying to "slc run" with having "oracle" as datasource i end up in same situation as was presented in the first message of this issue:
"WARNING: LoopBack connector "oracle" is not installed as any of the following modules."

Same error appears also when trying with arc.

I have installed visual studio express 2013 for desktop. I do not have python installed. Is that ok?

I can run "slc run" successfully if there is no "oracle" listed in the datasources.json. I have installed node and loopback with oracle drivers earlier in OS X with no issues. Looking at this issue with windows adding oracle db support to loopback seems to be causing issues not only for me, but others as well. I received no error messages when i ran "npm install loopback-connector-oracle --save", so troubleshooting this is impossible for me. Can you help me? I created this new issue as #27 was marked as closed.

**Comment by Tomkinen** [comment]
I also installed node and loopback according to instructions to linux. Same error appears also in my linux server.

WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

**Comment by superkhau** [comment]
Did you add `strong-oracle.rc` to your PATH?

**Comment by Tomkinen** [comment]
Thanks for the reply!

Can you be more precise? Do i need to do this in both windows and linux? Both installations are currently sharing the same error message of "loopback connector oracle is not installed". Adding strong-oracle.rc to path is not required thing to do in instructions (http://docs.strongloop.com/display/public/LB/Installing+the+Oracle+connector)? What exactly needs to be added to the path?

In windows i have in path at least these (i do not copy/paste those which are definitely not related somehow to strongloop):
C:\Python27\;
C:\Python27\Scripts;
C:\app\oracle\product\11.2.0\client_1\bin;
C:\Program Files (x86)\Git\cmd;
C:\Program Files\nodejs\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\loopback-projects\testproject06\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\loopback-projects\testproject06\node_modules\loopback-connector-oracle\node_modules\instantclient;
C:\Users\Tomi_admin\AppData\Roaming\npm

In linux i have just one folder added to path that is related to strongloop:
/opt/nodejs/bin

In linux i have updated the .bash_profile only as it is instructed as post installation setup in the oracle connector installation instructions.

**Comment by Tomkinen** [comment]
Now i found strong-oracle.rc from a different folder in linux. I then copied strong-oracle.rc to $HOME. Retried installing the connector and then i run "slc run". Same error appears.

**Comment by superkhau** [comment]
When you install the Oracle connector, `strong-oracle.rc` is generated in your home dir. You then need to source the file (ie. add `source ~/strong-oracle.rc` to your `bashrc`). These are instructions for Linux of course.

**Comment by superkhau** [comment]
@raymondfeng Is there Windows equivalent for sourcing `strong-oracle.rc`?

**Comment by raymondfeng** [comment]
On Windows, it will set up the PATH env var. See http://docs.strongloop.com/display/LB/Installing+the+Oracle+connector#InstallingtheOracleconnector-Windows

**Comment by superkhau** [comment]
I see, TY @Tomkinen ^

**Comment by Tomkinen** [comment]
Hi,

Appreciate that you quickly replied. Here are my replies for both linux and windows installations:

Linux:
1. Navigated to home: cd $HOME
2. Used vi .bash_profile and vi .bashrc to modify the files. Added strong-oracle.rc as a source.
3. Made sure that strong-oracle.rc exists in $HOME -folder.
4. Changed folder to project folder and run: slc run. Same error appears. "Loopback connector "oracle" is not installed as any of the following modules etc.".

Windows:
I have in the path these folders:
C:\Python27\;
C:\Python27\Scripts;
C:\app\oracle\product\11.2.0\client_1\bin;
C:\Program Files (x86)\Git\cmd;
C:\Program Files\nodejs\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\loopback-projects\testproject06\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\loopback-projects\testproject06\node_modules\loopback-connector-oracle\node_modules\instantclient;
C:\Users\Tomi_admin\AppData\Roaming\npm
...I cannot find "strong-oracle.rc" -file in the whole server.

In both linux and windows i have executed: npm install loopback-connector-oracle --save -command in the same folder i have the project and run the "slc run"-command successfully if i do only have "memory db" -connection from my models, not oracle db connections.

**Comment by Tomkinen** [comment]
Some additional information still.

Today we tried exactly the same steps i did in our windows server with colleagues own windows machine. He was able to install node, strongloop/loopback and oracle connector successfully.

I tried today to re-install node, strongloop and then created new loopback test instance. I was able to run it in localhost. Then i added oracle connector with 0 errors. Added model which uses oracle as source using "slc loopback:datasource" -command. I was able to select "oracle" from the list. Then i tried to start again the loopback with "slc run" and i STILL get the same old error that loopback connector oracle is not installed.

I have now tried with node version 10 and with version 12. I have visual studio desktop express and python 2.7.9. I have in my path the correct folders (i think):
C:\ORACLEtest001\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11
C:\ORACLEtest001\node_modules\loopback-connector-oracle\node_modules\instantclient

..slc loopback -project was added to ORACLEtest001 -folder.

In my own OS X installation and my colleagues windows installation oracle connector works ok. In both cases the default npm registry worked. In our server environment i had to run command:
sudo npm config set registry https://registry.nodejitsu.com

This was required thing to do because with original registry i was not able to load files. I got error:
"npm ERR! Error: failed to fetch from registry".. i Got this error from multiple files. When i changed the registry, there were no longer any fetch errors.

Hope this extra information helps.

**Comment by Tomkinen** [comment]
Still one more thing. Yesterday just tried to rename C:\ORACLEtest001\node_modules\loopback-connector-oracle\ -folder to C:\ORACLEtest001\node_modules\oracle.

End result was that error message changed to be from this:
---------
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error:
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle
--------------

To this:
-------------
C:\ORACLEtest001\node_modules\loopback-connector-oracle\lib\oracle.js:115
  this.driver.createConnectionPool(this.settings, function (err, pool) {
              ^
TypeError: undefined is not a function
    at Oracle.connect (C:\ORACLEtest001\node_modules\loopback-connector-oracle\lib\oracle.js:115:15)
-------------


Just trying out things to get this working. Hopefully also this helps troubleshooting this.

**Comment by raymondfeng** [comment]
When you rename the folder, you need to update the PATH env var so that Oracle instant client DLLs are available on the PATH. Can you dump out its value using `echo %PATH%` to make sure?

**Comment by Tomkinen** [comment]
To correct my earlier post, i did COPY the "loopback-connector-oracle" -folder and renamed the copied folder to be just "oracle". So end result was that i had both "loopback-connector-oracle"-folder AND "oracle"-folder under "node_modules". Then error message changed as stated in my earlier post. If i remove "oracle" -folder then the error message returns to be the original error message.

path=
C:\ORACLEtest001\>echo %PATH%
C:\Python27\;C:\Python27\Scripts;C:\app\oracle\product\11.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
tem32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;c:\curl;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\7-Z
ip;C:\Program Files (x86)\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\M
icrosoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\ORACLEtest001\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;C:\ORACLEtest001\node_modules\loopback-
connector-oracle\node_modules\instantclient;C:\Users\Tomi_admin\AppData\Roaming\npm;C:\Program Files\instantclient_12_1

**Comment by girishla** [comment]
I have the same issue - did you end up fixing this @Tomkinen ?

**Comment by Tomkinen** [comment]
Hi @girishla !

I ended up choosing other solution than loopback/strongloop to create the backend API. So unfortunately i do not have a solution for this particular issue.

**Comment by girishla** [comment]
@Tomkinen just realized I had multiple versions of Node installed on my machine...one of which was 4.x
I uninstalled 4.x and voila...it worked! no error.

**Comment by chenulu** [comment]
I am getting the following errors on Mac OS 10.10.5, node v0.12.4

ERR WARNING: LoopBack connector "oracle" is not installed as any of the following modules:
 ERR  ./connectors/oracle
ERR loopback-connector-oracle
ERR To fix, run:
ERR     npm install loopback-connector-oracle
ERR events.js:85
ERR       throw er; // Unhandled 'error' event
ERR             ^
ERR Error:
ERR WARNING: LoopBack connector "oracle" is not installed as any of the following modules:
ERR  ./connectors/oracle
ERR loopback-connector-oracle
ERR To fix, run:
ERR     npm install loopback-connector-oracle

As mentioned in one of the posts by raymondfeng, tried the commands below

 git clone http://github.com/strongloop/strong-oracle.git
Cloning into 'strong-oracle'...
remote: Counting objects: 1506, done.
remote: Total 1506 (delta 0), reused 0 (delta 0), pack-reused 1506
Receiving objects: 100% (1506/1506), 368.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (963/963), done.
Checking connectivity... done.

[kailash@Aryabhatta] ~/stuff/CustomerApps/StrongOracle
$ cd strong-oracle

[kailash@Aryabhatta] ~/stuff/CustomerApps/StrongOracle/strong-oracle (master)
$ npm i
npm WARN package.json strong-oracle@1.7.0 license should be a valid SPDX license expression

> segfault-handler@0.2.5 install /Users/kailash/stuff/CustomerApps/StrongOracle/strong-oracle/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node
  SOLINK_MODULE(target) Release/segfault-handler.node: Finished

> strong-oracle@1.7.0 install /Users/kailash/stuff/CustomerApps/StrongOracle/strong-oracle
> node-gyp rebuild

  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
In file included from ../src/connection.cpp:2:
../src/connection.h:10:10: fatal error: 'occi.h' file not found
#include <occi.h>
         ^
1 error generated.
make: *** [Release/obj.target/oracle_bindings/src/connection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kailash/stuff/CustomerApps/StrongOracle/strong-oracle
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! strong-oracle@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strong-oracle@1.7.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the strong-oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls strong-oracle
npm ERR! There is likely additional logging output above.

I have already sourced strong-oracle.rc and also ran 

npm install loopback-connector-oracle

Any pointers are appreciated.

**Comment by dnirchi** [comment]
When I try testing the connection in Arc on Mac, I get the following error (I've followed the Oracle connector setup instructions for Mac and have spent several hours troubleshooting this):

Oops! Something is wrong
Connector "oracle" is not installed.
Add the connector to your project, configure the environment variables, restart Arc and try again. See docs: Installing the Oracle connector for more information.
Show/hide details
Name: InvocationError
Message: Connector "oracle" is not installed.
Request: /workspace/api/DataSourceDefinitions/server.oracle-test/testConnection
Staus: 500

**Comment by raymondfeng** [comment]
Please make sure you have the env var `DYLD_LIBRARY_PATH` configured correctly, for example:
```
DYLD_LIBRARY_PATH=/Users/rfeng/Projects/myapp/node_modules/loopback-connector-oracle/node_modules/instantclient
```
The oracle connector creates `~/strong-oracle.rc` during the installation. You can enable it to your `.bash_profile` as follows:

```
if [ -f ~/strong-oracle.rc ]; then
  source ~/strong-oracle.rc
fi
```

**Comment by dnirchi** [comment]
Thanks for the quick response! By the way, I'm running node v0.12.2 on Mac OS v10.11.

I have DYLD_LIBRARY_PATH set:

$ echo $DYLD_LIBRARY_PATH
:/Users/nirchi/Development/strongloop/oracle-test/node_modules/loopback-connector-oracle/node_modules/instantclient

Inside my .bash_profile, I have:

if [ -f ~/strong-oracle.rc ]; then
  source ~/strong-oracle.rc
fi

I've done a "source" on both my .bash_profile and the generated ~/strong-oracle.rc files.

I've restarted StrongLoop Arc, but I am still seeing the following when I click "Test Connection" in trying to create a new Oracle data source:

Name: InvocationError
Message: Connector "oracle" is not installed.
Request: /workspace/api/DataSourceDefinitions/server.oracledb/testConnection
Staus: 500
InvocationError: Connector "oracle" is not installed.
    at missingConnector (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/models/data-source-definition.js:358:13)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/models/data-source-definition.js:313:19)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

**Comment by dnirchi** [comment]
I believe I know what the issue is as it pertains to running the Oracle connector on a Mac - it doesn't appear to work on El Capitan, but does work on Yosemite. Here are the steps to recreate the problem.

1. On a Mac running OS X Yosemite, install StrongLoop and scaffold a new Loopback application ('slc loopback').
2. Install the loopback-connector-oracle NPM package into said application.
3. Start StrongLoop Arc for the app and create a new Oracle datasource and test the connection.
4. Close down the application and upgrade the OS to El Capitan.
5. After the upgrade, restart StrongLoop Arc for the same application.
6. Test the Oracle database connection again and you should see the infamous "Connector "oracle" is not installed." error message.

Can anyone else confirm this?

**Comment by superkhau** [comment]
@cgole Can you help verify the STR by @dnirchi? I am on El Capitan and I'm also running into issues locally ATM. I had it working on Yosemite.

**Comment by dnirchi** [comment]
@superkhau @raymondfeng @cgole Could this node-oracledb issue be the root cause?

[#231](https://github.com/oracle/node-oracledb/issues/231)

**Comment by superkhau** [comment]
@dnirchi Nice catch. Guess we'll have to wait to see what the community is doing about it.

**Comment by raymondfeng** [comment]
Do you use node-oracledb instead of strong-oracle?

**Comment by dnirchi** [comment]
@raymondfeng

We've established that the StrongLoop Oracle connector will not work on El Capitan due to [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) runtime protections and restrictions. Specifically, DYLD environment variables are now ignored; hence, rendering the Oracle connector inoperable due to the DYLD_LIBRARY_PATH dependency.

See my earlier comment on a temporary workaround.

**Comment by crandmck** [comment]
I added the above note to docs: https://docs.strongloop.com/display/LB/Oracle+connector.
If this is fixed, _please_ let me know so I can update docs accordingly.

**Comment by superkhau** [comment]
@crandmck Your note looks good. We should make note of the workaround by @dnirchi for now. See http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

**Comment by crandmck** [comment]
Added link to workaround.

**Comment by ikogan** [comment]
In the above issue, I did a bit of investigation and `strong-oracle` *does* work with the environment variable set if a script is run directly from node. It *does not* work if started with `slc`, or some other tool that _seems_ to wrap node.

In addition, disabling all of SIP isn't necessary, only debugging restrictions:

```
kogan@dhcp-196-145 ~/Documents/Code/loopback-oracle-installer $ csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: enabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

I'm not sure if my configuration is somehow magical and allowing it to work directly from node.

**Comment by p-somers** [comment]
Anyone have any updates on this? I have SIP protection disabled, got the connector installed, have the node module present (through npm install loopback-connector-oracle) but I still get the "LoopBack connector 'oracle' is not installed" error

**Comment by hamiddivandari** [comment]
Please fix this problem. 
I have the same problems as others . 
I 've installed loopback-connector-oracle but I still get the "LoopBack connector 'oracle' is not installed" error.
Thanks

**Comment by mrmr68** [comment]
I'm working on a project using loopback.
i need oracle connector to connect my models. but it seems not installed , i think it's a wrong error because it installed successfully.
please fix this problem .
thanks

**Comment by superkhau** [comment]
@hamiddivandari Do your models connect correctly like @mrmr68 (while the app still reports error)?

**Comment by samhenri** [comment]
Tried with Windows 10 and Oracle XE and I'm facing the same issue. Is there any workaround?

**Comment by ExTheSea** [comment]
Just a heads up. I just got it working on a Windows Server 2012 by:
- Installing the latest 64bit NodeJS 6 version
- Installing Visual C++ 2010 Redistributable x64
- Downloading instanclient-basic-windowsx64 and instantclient-sdk-windowsx64 and extracting the contents of both intantclient_12... folders into C:/oracle/instantclient (so that the vc10, vc11 and the help and sdk folders are both inside c:/oracle/instantclient)
- Adding C:/oracle/instantclient to my PATH
- Make sure you restart your cmd

Might work with the instantclient bundled with the connector as well. Also might be able with a different Visual C++ Redistributable but using the 2008, 2012 and 2015 ones i had previously it didn't work.

**Comment by kartsims** [comment]
Can't get it working either on Linux

- Oracle InstantClient installed (v12.2) including Basic, ODBC, SQLPlus and Devel packages
- `LD_LIBRARY_PATH` exported and valid
- package installed

Still getting :

```
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle --save

/var/nodejs/node_modules/loopback/lib/application.js:237
    throw err;
    ^
```

**Comment by kartsims** [comment]
@p-somers @hamiddivandari @samhenri did you guys manage to get it working ?

**Comment by samhenri** [comment]
I was not able to run it on a windows 7 machine at work but on my personal computer with Windows 10 it worked after I've reinstalled the Visual C++ Redistributable (don't recall the version). I think some of my company softwares are to blame.

**Comment by kartsims** [comment]
Thanks @samhenri for the feedback.

**I managed to solve the issue on Linux Debian by installing `oracledb` PRIOR TO `loopback-connector-oracle`**

This should definetely be stated somewhere in the docs. Also, the most complete doc I found was on [`loopback-oracle-installer`](https://github.com/strongloop/loopback-oracle-installer/)'s README page.

I lost a few hours looking around for this, I hope it will help others !

**Comment by kartsims** [comment]
@crandmck yes it is incorrect, didn't work on my setup.

The installation of `oracledb` probably failed on my setup but I didn't get warnings. Or i I might have got any, it got lost on the way.

Failing to install `oracledb` should prevent the package from installing IMO.

**Comment by crandmck** [comment]
@raymondfeng @rashmihunt @superkhau Please advise. This sounds like a bug rather than a doc issue but we need confirmation.

**Comment by superkhau** [comment]
@rashmihunt Would know best I think as she created the instructions awhile back.
