### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by providabhi** [strongloop/loopback-connector-oracle#39]
Hi,

While trying to install the connector with Node (v0.12.0) and npm (v2.9.1), i am getting the following error

C:\TD\USTS\NodeWorkspaces\DBConnect>npm install loopback-connector-oracle --save

\
> loopback-oracle-installer@1.4.0 install C:\TD\USTS\NodeWorkspaces\DBConnect\no
de_modules\loopback-connector-oracle\node_modules\loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f575
1b6.r22.cf1.rackcdn.com/loopback-oracle-Windows-x86-abi14-1.5.0.tar.gz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:366:17)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Redirection\\arathor\\AppData\\npm\\node_module
s\\npm\\bin\\npm-cli.js" "install" "loopback-connector-oracle" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@1.4.0 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@1.4.0 install script 'node pkgi
nstall.js'.
npm ERR! This is most likely a problem with the loopback-oracle-installer packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\TD\USTS\NodeWorkspaces\DBConnect\npm-debug.log

**Comment by raymondfeng** [comment]
Are you on a 32 bit Windows? If so, we haven’t published a prebuilt image for the driver.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by providabhi** [comment]
I have 64 bit WIndows 7 Enterprise Edition. However the Node JS i have is 32 bit. 

The loopback-connector-oracle is only for 64-bit versions?

**Comment by raymondfeng** [comment]
You should install the 64 bit Node. We start to deprecate the 32 bit support as iojs doesn't ship 32 bit version for Windows.

**Comment by providabhi** [comment]
Thanks! I was able to do a install with 64 bit version of Node.

However now when I do a simple project using strongloop, it looks like it ws not properly installed, even though it said it did.
--> slc loopback
--> Create the data source on "slc arc" and do "Test Connection", i get the following error
--> package.json has 
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "loopback": "^2.14.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-oracle": "^1.7.2",
    "loopback-datasource-juggler": "^2.19.0",
    "serve-favicon": "^2.0.1"
  },

Oops! Something is wrong

Connector "oracle" is not installed.

Add the connector to your project, configure the environment variables,  restart Arc and try again.  See docs: Installing the Oracle connector for more information. 

Show/hide details

Name: InvocationError
Message: Connector "oracle" is not installed.
Request: /workspace/api/DataSourceDefinitions/server.HostStateDB/testConnection
Staus: 500
InvocationError: Connector "oracle" is not installed.
    at missingConnector (C:\Users\Redirection\<user>\AppData\npm\node_modules\strongloop\node_modules\loopback-workspace\models\data-source-definition.js:358:13)
    at ChildProcess.<anonymous> (C:\Users\Redirection\<user>\AppData\npm\node_modules\strongloop\node_modules\loopback-workspace\models\data-source-definition.js:313:19)
    at ChildProcess.g (events.js:180:16)
    at ChildProcess.emit (events.js:98:17)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)

**Comment by providabhi** [comment]
so if I do "slc run", i get the error. I have tried installing the loopback-connector-oracle quite a few times. taken the steps for Windows at following link:
http://docs.strongloop.com/display/public/LB/Installing+the+Oracle+connector


WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error:
WARNING: LoopBack connector "oracle" is not installed as any of the following mo
dules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

**Comment by raymondfeng** [comment]
Can you dump out the env vars for PATH to check if the Oracle instant client DLLs are on the path?

**Comment by providabhi** [comment]
yes i can see the instant client on my PATH installed by loopback-connector-oracle
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient;

The following the the path (echo %PATH%) on my windows (x64) machine

C:\Users\Redirection\<user>\AppData\npm;
C:\AR\Software\PYTHON27\;
C:\AR\Software\PYTHON27\Scripts;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Microsoft Application Virtualization Client;
C:\Program Files (x86)\Enterprise Vault\EVClient\;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;
C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files\Lenovo\Fingerprint Manager Pro\;
C:\PROGRA~2\INTEGR~1\Toolkit\mksnt;
C:\AR\Software\PuTTY;
c:\AR\software\java\8u11\jre\bin;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\MicrosoftSQL Server\120\Tools\Binn\;
C:\AR\Software\Node\nodejs_1038_64\;
C:\AR\USTS\NodeWorkspaces\DBConnect\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\AR\USTS\NodeWorkspaces\DBConnect\node_modules\loopback-connector-oracle\node_modules\instantclient;
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient;
C:\AR\Software\Tools\Ant170\bin;
C:\AR\Software\Tools\Maven311\bin;
C:\Users\Redirection\<user>\AppData\npm;
C:\AR\Software\PYTHON27\;
C:\AR\Software\PYTHON27\Scripts;
C:\Program Files (x86)\Integrity\IntegrityClient10\bin;
C:\Program Files (x86)\RSA SecurID Token Common;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Microsoft Application Virtualization Client;
C:\Program Files (x86)\Enterprise Vault\EVClient\;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;
C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files\Lenovo\FingerprintManager Pro\;
C:\PROGRA~2\INTEGR~1\Toolkit\mksnt;
C:\AR\Software\PuTTY;
%JAVA_HOME%\bin;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\AR\Software\Node\nodejs_1038_64\;
C:\AR\USTS\NodeWorkspaces\DBConnect\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\AR\USTS\NodeWorkspaces\DBConnect\node_modules\loopback-connector-oracle\node_modules\instantclient;
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient\vc11;
C:\Users\Redirection\<user>\AppData\npm\node_modules\loopback-connector-oracle\node_modules\instantclient;
%ANT_HOME%\bin;
%M2_HOME%\bin;
%PATH%

**Comment by providabhi** [comment]
just trying to make sure around the versions i have installed

Node (v0.10.38)
NPM (v1.4.28)
loopback-connector-oracle(v1.7.2)
strongloop v4.0.2 (node v0.10.38)
├── strong-arc@1.2.1 (a6c841f)
├── strong-build@2.0.0 (0cb88da)
├── strong-deploy@2.2.0 (ada97d4)
├── strong-pm@4.1.0 (4629260)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.1.0 (04195e6)
├─┬ strong-supervisor@1.6.0 (baa3fcd)
│ └── strong-agent@1.5.1
├── generator-loopback@1.9.1 (5219ef1)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

is there any plce where i can verify if this versions are a correct match to be working in sync with each other.

**Comment by providabhi** [comment]
Anyone has inputs to have this connector working...

**Comment by raymondfeng** [comment]
What VisualStudio version do you have?

**Comment by providabhi** [comment]
I have Visual Studio 2013

**Comment by providabhi** [comment]
Express 2013 for Windows Desktop

https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx

**Comment by raymondfeng** [comment]
I have VS 2012. It might be the case that VS 2013 is not compatible with Oracle Instant Client.

**Comment by providabhi** [comment]
Ok.. Thanks! 

Would this connector be supported with latest Node JS(v0.12.x)?

**Comment by providabhi** [comment]
Thanks! Works good now with VS 2012.
