### ISSUE TITLE
LoopBack connector "oracle" is not installed (but it is) - UBUNTU

### ISSUE THREAD

**Issue by ryedin** [strongloop/loopback-connector-oracle#41]
Something is very wrong with the install procedure. I cannot seem to get it to work.

Firstly, no strong-oracle.rc file is generated (even though the install script says it is)...

Notice the first few lines in the output below (the install.sh script is erroring with `bad substitution`, yet the script happily announces the file was generated...)

```
> loopback-oracle-installer@1.4.0 install /vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi14-1.5.0.tar.gz
http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi14-1.5.0.tar.gz is now extracted to /vagrant/node_modules/loopback-connector-oracle/node_modules
/vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: 5: /vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: Bad substitution
/vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: 7: /vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: source: not found
/vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: 9: /vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/bin/installers/Linux/installer.sh: setup_configuration: not found
-------------------------------------------------------------------------------
"strong-oracle.rc" has been created in $HOME. Please manually add the
following to your ".bash_profile":

  source /home/vagrant/strong-oracle.rc

If you do not use bash as your default shell, please remember to set
$LD_LIBRARY_PATH prior to using node:

  export LD_LIBRARY_PATH=":/vagrant/node_modules/loopback-connector-oracle/node_modules/instantclient"

The node-oracle module and Oracle specific libraries have been installed in
/vagrant/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer. Alternatively, you can add that path to /etc/ld.so.conf (sudo required):

  echo "/vagrant/node_modules/loopback-connector-oracle/node_modules/instantclient" | sudo tee -a /etc/ld.so.conf.d/loopback_oracle.conf
  sudo ldconfig

-------------------------------------------------------------------------------
loopback-connector-oracle@2.1.0 node_modules/loopback-connector-oracle
├── sl-blip@1.0.0
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── strongloop-license@1.1.0 (user-home@1.1.1, strong-license@1.1.0)
├── loopback-connector@2.2.1 (async@1.1.0)
└── loopback-oracle-installer@1.4.0 (graceful-fs@3.0.8, tar@1.0.3, fstream@1.0.6, buffered-stream@0.0.1, request@2.57.0)

```

So, then I figured I could manually export the `LD_LIBRARY_PATH` variable and run the app, to no avail. Then I tried manually creating the `strong-oracle.rc` file and adding the export to that file (and sourcing)... no luck.

No matter what I've tried, we keep getting the following: 

```
Error: 
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

    at DataSource.setup (/vagrant/node_modules/loopback-datasource-juggler/lib/datasource.js:294:28)
    at new DataSource (/vagrant/node_modules/loopback-datasource-juggler/lib/datasource.js:101:8)
    at Registry.createDataSource (/vagrant/node_modules/loopback/lib/registry.js:323:12)
    at dataSourcesFromConfig (/vagrant/node_modules/loopback/lib/application.js:386:19)
    at EventEmitter.app.dataSource (/vagrant/node_modules/loopback/lib/application.js:221:12)
    at /vagrant/node_modules/loopback-boot/lib/executor.js:158:9
    at /vagrant/node_modules/loopback-boot/lib/executor.js:228:5
    at Array.forEach (native)
    at forEachKeyedObject (/vagrant/node_modules/loopback-boot/lib/executor.js:227:20)
    at setupDataSources (/vagrant/node_modules/loopback-boot/lib/executor.js:157:3)

```

**Comment by raymondfeng** [comment]
The bottom line is that `LD_LIBRARY_PATH` should be pointing to `/vagrant/node_modules/loopback-connector-oracle/node_modules/instantclient`. Can you run the following commands to make sure?

1. ls -l /vagrant/node_modules/loopback-connector-oracle/node_modules/instantclient
2. echo $LD_LIBRARY_PATH

**Comment by ryedin** [comment]
Yes, that value was fine.

We just figured out the (main) issue. To get more information about what was going wrong, we first ran `cd node_modules/loopback-connector-oracle/node_modules/strong-oracle/` and then tried `node example/app.js` to see if we could get more helpful messaging as to the issue.

That gave us:

```
error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
```

Which helped us find other people having issues (with other libs) related to having a 32bit version of libaio. It turns out that even though we are using 64bit Ubuntu (14.04) - for some odd reason the default version of that lib is 32bit. This is a fresh, newly updated Ubuntu machine (managed via vagrant).

In short, running `sudo apt-get install libaio1` cleared the problem up for us.

So... not sure how you could possibly encapsulate detection/resolution of this for other Ubuntu users (possibly linux in general??)... but maybe call it out in the docs as I can imagine a lot of folks getting burned here.

The other issue of the installer not properly generating the `strong-oracle.rc` file is another story. Frankly, if all that's needed is to set that env variable, I'm not sure why you are attempting to generate that file in $HOME anyway. Why not just spit out directions telling the user to add that line to the bash profile script (especially since we also need to manually change the bash profile script to source the `strong-oracle.rc` file anyway)?

**Comment by raymondfeng** [comment]
Please note that the libaio requirement is mentioned in the README:
```
libaio library is required on Linux systems:

On Ubuntu/Debian

﻿sudo apt-get install libaio1
On Fedora/CentOS/RHEL

﻿sudo yum install libaio
```

**Comment by ryedin** [comment]
Ah OK... sorry then.

Didn't dig into the repo's README. We came in via the main docs: (http://docs.strongloop.com/display/public/LB/Installing+the+Oracle+connector)

**Comment by raymondfeng** [comment]
I just updated the docs.
