### ISSUE TITLE
StrongLoop Enterprise Connector

### ISSUE THREAD

**Issue by OscarValdez** [strongloop/loopback-connector-oracle#43]
As everybody knows Strongloop uses this open source connector as bridge to oracle data, but i got a question. In the page of pricing of strongloop it says that the Open Source Drivers are free, but they have a Enterprise Connectors section in that section they manage Oracle.

Does the Loopback oracle connector is the same as the enterprise connector from LoopBack?

Can anyone has a project with Strongloop using this driver ? do you pay for it ?

Thanks in advance.

**Comment by raymondfeng** [comment]
1. The driver is dual-licensed - https://github.com/strongloop/strong-oracle
2. The connector is StrongLoop licensed - https://github.com/strongloop/loopback-connector-oracle

**Comment by RogelioGaytan** [comment]
I also have a similiar doubt.

For doing conection and modeling for oracle databases using stroongloop arc, do you need the enterprise connector mandatory?

Or What are the open source connectors?


Do you know @raymondfeng?
