### ISSUE TITLE
How to create an out parameter

### ISSUE THREAD

**Issue by jgauna** [strongloop/loopback-connector-oracle#46]
I've the doc but coulnd't find out to execute store procedures. Then I find out doing:

```
		sqlLogin = 'var c NUMBER; var d VARCHAR2(20); execute WEBAPPPORTALPM.pk_portal_n.login(' + loginType + ', ' + username + ', ' + password + ', :c, :d);';
		var result = dataSource.connector.execute(sqlLogin, function(err, response) {
			cb(null, "response: login success");
		});
```

But here's where I need two out parameters. Is there any way to achive this?

Thanks!

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strong-oracle/blob/master/test/outparams.js

**Comment by jgauna** [comment]
This is not working. I have this:

```
var path = require('path'),
	app = require(path.resolve(__dirname, '../../server/server')),
	dataSource = app.dataSources.accountDs,
	settings = require('../../server/dbConfig'),
	oracle = require('loopback-connector-oracle/lib/oracle');

module.exports = function(user) {
	var sqlLogin;
	user.login = function(loginType, username, password, cb) {
		sqlLogin = 'execute login(' + loginType + ', ' + username + ', ' + password + ', :1, :2);';
		var result = dataSource.connector.execute(sqlLogin, [loginType,
			username,
			password,
			new oracle.OutParam(oracle.OCCIINT),
			new oracle.OutParam(oracle.OCCISTRING)
		], function(err, response) {
			cb(null, "response: login success");
		});
	};

	user.remoteMethod('login', {
		http: {
			errorStatus: 400,
			verb: 'post',
			status: 201
		},
		accepts: [{
			arg: 'loginType',
			type: 'string'
		}, {
			arg: 'username',
			type: 'string'
		}, {
			arg: 'password',
			type: 'string'
		}],
		returns: [{
			arg: 'response',
			type: 'string'
		}]
	});
};
```

And in ```dbConfig.js```:

```
module.exports = {
    host: "ip",
    port: 1521,
    database: "database",
    username: "user",
    password: "pass",
    name: "accountDs",
    connector: "oracle",
    user: "user"
};
```

I get:

```TypeError: object is not a function```

And the connection is working because I got data if I do any kind of plain select.

Thanks for the help

**Comment by jgauna** [comment]
How do I implement this in oracle connector? Could you give me a full example? Not working that example (it's strong-oracle)

**Comment by raymondfeng** [comment]
```js
var oracle = dataSource.connector.driver;
var intParam = new oracle.OutParam(oracle.OCCIINT);
```

**Comment by pchiguruvada** [comment]
Any solution to implement this in loopback-connector-oracle please

**Comment by pchiguruvada** [comment]
> I've the doc but coulnd't find out to execute store procedures. Then I find out doing:
> 
> ```
>         sqlLogin = 'var c NUMBER; var d VARCHAR2(20); execute WEBAPPPORTALPM.pk_portal_n.login(' + loginType + ', ' + username + ', ' + password + ', :c, :d);';
>         var result = dataSource.connector.execute(sqlLogin, function(err, response) {
>             cb(null, "response: login success");
>         });
> ```
> 
> But here's where I need two out parameters. Is there any way to achive this?
> 
> Thanks!

Hi jgauna, 
Were you able to find a solution for this. If so could you please help me.

**Comment by raymondfeng** [comment]
The 2nd arg for execute can be an array of parameters for the stored procedure.
