### ISSUE TITLE
Asking for license

### ISSUE THREAD

**Issue by OscarValdez** [strongloop/loopback-connector-oracle#47]
Can i use this connector to produce a comercial product for free? 

A) With te use of strongloop
B) only With loopback

Thank you in advance

**Comment by superkhau** [comment]
@dashby3000 

/cc @raymondfeng ^

**Comment by altsang** [comment]
@OscarValdez - the Oracle connector for LoopBack requires a commercial subscription.  If you're interested feel free to drop us a line at sales @ strongloop.com.  We have subscriptions plans for developers and companies of all sizes.

**Comment by superkhau** [comment]
Closing as resolved.
