### ISSUE TITLE
connector install failed on MAC OSX

### ISSUE THREAD

**Issue by swizardlv** [strongloop/loopback-connector-oracle#48]
Dear, I have downloaded and configured the strong-oracle following the guide.
then run `npm install loopback-connector-oracle --save` and got following error.
![image](https://cloud.githubusercontent.com/assets/10117682/9899361/dbabeb9a-5c8b-11e5-9535-c49f7c111cc4.png)
seems build error. Please help . Thanks.
the following is the debug log: the log is too long, i only pasted the error part.

 6676 verbose about to build /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle
6677 verbose unlock done using /Users/swizard/.npm/_locks/loopback-connector-oracl-a5c44909a0f9120a.lock for /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle
6678 verbose stack Error: loopback-oracle-installer@1.4.1 install: `node pkginstall.js`
6678 verbose stack Exit status 1
6678 verbose stack     at EventEmitter.<anonymous> (/Users/swizard/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
6678 verbose stack     at emitTwo (events.js:87:13)
6678 verbose stack     at EventEmitter.emit (events.js:172:7)
6678 verbose stack     at ChildProcess.<anonymous> (/Users/swizard/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
6678 verbose stack     at emitTwo (events.js:87:13)
6678 verbose stack     at ChildProcess.emit (events.js:172:7)
6678 verbose stack     at maybeClose (internal/child_process.js:764:16)
6678 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
6679 verbose pkgid loopback-oracle-installer@1.4.1
6680 verbose cwd /Users/swizard/Documents/dev/strongloop
6681 error Darwin 14.5.0
6682 error argv "/Users/swizard/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/swizard/.nvm/versions/io.js/v2.5.0/bin/npm" "install" "loopback-connector-oracle" "--save"
6683 error node v2.5.0
6684 error npm  v2.13.2
6685 error code ELIFECYCLE
6686 error loopback-oracle-installer@1.4.1 install: `node pkginstall.js`
6686 error Exit status 1
6687 error Failed at the loopback-oracle-installer@1.4.1 install script 'node pkginstall.js'.
6687 error This is most likely a problem with the loopback-oracle-installer package,
6687 error not with npm itself.
6687 error Tell the author that this fails on your system:
6687 error     node pkginstall.js
6687 error You can get their info via:
6687 error     npm owner ls loopback-oracle-installer
6687 error There is likely additional logging output above.
6688 verbose exit [ 1, true ]
6689 verbose unbuild node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
6690 info preuninstall loopback-oracle-installer@1.4.1
6691 info uninstall loopback-oracle-installer@1.4.1
6692 verbose unbuild rmStuff loopback-oracle-installer@1.4.1 from /Users/swizard/Documents/dev/strongloop/node_modules
6693 verbose unbuild rmStuff in /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle/node_modules
6694 info postuninstall loopback-oracle-installer@1.4.1
6695 silly gentlyRm /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer is being purged from base /Users/swizard/Documents/dev/strongloop
6696 verbose gentlyRm don't care about contents; nuking /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
6697 silly vacuum-fs purging /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
6698 silly vacuum-fs quitting because other entries in /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle/node_modules
6699 verbose unbuild node_modules/loopback-connector-oracle
6700 info preuninstall loopback-connector-oracle@2.2.0
6701 info uninstall loopback-connector-oracle@2.2.0
6702 verbose unbuild rmStuff loopback-connector-oracle@2.2.0 from /Users/swizard/Documents/dev/strongloop/node_modules
6703 info postuninstall loopback-connector-oracle@2.2.0
6704 silly gentlyRm /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle is being purged from base /Users/swizard/Documents/dev/strongloop
6705 verbose gentlyRm don't care about contents; nuking /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle
6706 silly vacuum-fs purging /Users/swizard/Documents/dev/strongloop/node_modules/loopback-connector-oracle
6707 silly vacuum-fs quitting because other entries in /Users/swizard/Documents/dev/strongloop/node_modules

**Comment by raymondfeng** [comment]
We don't have pre-built binary dependencies for iojs-2.5.0. Can you use iojs-3.0.0? We're working on the support for node 4.0.0.

**Comment by swizardlv** [comment]
thanks for reply.

I tried iojs-3.0.0 and iojs-3.3.0 , had the same error.

**Comment by dnguyenv** [comment]
Any update you this please? I'm getting same error, on Mac

**Comment by raymondfeng** [comment]
Which os/node version?

**Comment by dnguyenv** [comment]
Mac 10.10.5
Node v4.2.2
