### ISSUE TITLE
open source this connector

### ISSUE THREAD

**Issue by bchr02** [strongloop/loopback-connector-oracle#49]
Just curious what the plan was for switching to using [node-oracledb](https://github.com/oracle/node-oracledb) as the driver and whether there are any plans for open sourcing this connector? Paying a couple hundred dollars monthly just to be able to use this connector seems crazy (at least for a small business) and in my opinion will drive prospective users (such as myself) away from using loopback. 

If it were open sourced, I think eventually, after becoming more dependent on loopback, some of these same users would be more willing to pay for a monthly fee.

**Comment by superkhau** [comment]
@ijroth ^

**Comment by raymondfeng** [comment]
This branch has working code for oracledb - https://github.com/strongloop/loopback-connector-oracle/tree/feature/oracledb

**Comment by bchr02** [comment]
thanks @raymondfeng I'll have a look. How about my main concern?
>any plans for open sourcing this connector

**Comment by raymondfeng** [comment]
@bchr02 Can you send an email to callback@strongloop.com for the license discussion?

**Comment by superkhau** [comment]
@bchr02 Closing this issue. As suggested by @raymondfeng, feel free to send an email to callback@strongloop.com for license discussions.
