### ISSUE TITLE
Support latest version(s) of Node.js.

### ISSUE THREAD

**Issue by dnirchi** [strongloop/loopback-connector-oracle#52]
When can we expect compatibility with more recent versions of Node.js (ie: 4.2.2 and/or 5.1.0)?

Maintaining a legacy version of Node.js just for the Oracle connector adds complexity to the development process and the provisioning of production systems. It seems reasonable to expect the connector to stay relatively current with the most recent version of Node.js, in the same manner the rest of the StrongLoop ecosystem does.

**Comment by raymondfeng** [comment]
`strong-oracle` already supports node 4.x/5.x. We need to pre-build the binaries and make them available to CDN so that they can be downloaded as part of `npm install`.

**Comment by dnirchi** [comment]
Thanks, @raymondfeng. I will give that a shot and let you know if I run into any issues.

**Comment by dnirchi** [comment]
@raymondfeng When can we expect an update to the node-oracle MacOSX/Linux/Windows bundles on the Rackspace CDN?
