### ISSUE TITLE
Cannot use locally compiled strong-oracle and no package available?

### ISSUE THREAD

**Issue by ikogan** [strongloop/loopback-connector-oracle#53]
Since `loopback-connector-oracle` now uses `loopback-oracle-installer` to download and install `strong-oracle`, is there no way to use `strong-oracle` without building it and hosting it in some location for it to download?

`strong-oracle` seems to build and work fine on my El Capitan machine (despite the warning in the docs) yet the URL at which `loopback-oracle-installer` tries to download the package (http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi47-1.5.0.tar.gz) is a 404.

**Comment by raymondfeng** [comment]
Which node version do you use?

**Comment by raymondfeng** [comment]
We need to publish the prebuilt binaries to Rackspace for node 5.x.

**Comment by ikogan** [comment]
You guessed it, 5.1.0 ;-). In the mean time, is there any way to convince the connector to use the `strong-oracle` I've compiled?

**Comment by ikogan** [comment]
I made the change above to `loopback-oracle-installer` (and plan on a PR when I can make sure it's working properly). I then ran

```
npm install strong-oracle
npm install loopback-oracle-installer@../loopback-oracle-installer
npm install loopback-connector-oracle
```

All of these now claim to have installed properly and my `node_modules` looks like this:

```
kogan@Panchreston ~/Documents/Code/strongloop $ ls node_modules/
compression                 jshint                      loopback-connector-oracle   loopback-oracle-installer
cors                        loopback                    loopback-datasource-juggler serve-favicon
errorhandler                loopback-boot               loopback-explorer           strong-oracle
```

When I try to run my project though, it doesn't seem to see the connector:

```
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

events.js:141
      throw er; // Unhandled 'error' event
      ^
```

**Comment by ikogan** [comment]
So it looks like this latest problem is due to OS 10.11 El Capitan's SIP protections. It seems "debugging restructions" prevent `DYLD_LIBRARY_PATH` from propagating from the `slc` launcher or something?

Anyway, `csrutil enable --without debug` seems to solve this problem. I'll submit the PR.

**Comment by superkhau** [comment]
May be related to https://github.com/strongloop/loopback-connector-oracle/issues/37#issuecomment-150020202

**Comment by ikogan** [comment]
Totally, thanks for the link.
