### ISSUE TITLE
npm install loopback-connector-oracle zlib issue on ubuntu 14.x & RH 7

### ISSUE THREAD

**Issue by smartmouse** [strongloop/loopback-connector-oracle#54]
/home/nodebot/testpm12
$ cd ..
$ cd testarc12
$ npm install loopback-connector-oracle --save
\

> loopback-oracle-installer@1.4.1 install /home/nodebot/testarc12/node_modules/l                           oopback-connector-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f575                           1b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-ppc64-abi14-1.5.0.tar.gz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:366:17)
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/home/nodebot/IBMSVT64_12/bin/node" "/home/nodebot/IBMSVT64_12/bi                           n/npm" "install" "loopback-connector-oracle" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@1.4.1 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@1.4.1 install script 'node pkgi                           nstall.js'.
npm ERR! This is most likely a problem with the loopback-oracle-installer packag                           e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodebot/testarc12/npm-debug.log
$ ^C
$

detailed 
https://gist.github.com/smartmouse/f97f1de02e0ba9b5fa25

same issue ppcLE RH 7

https://gist.github.com/smartmouse/eef4cdd8f5542abc4c11

**Comment by priyavivek1** [comment]
Is there any update on same. I am getting same error on RED HAT with node 0.10.39

**Comment by smartmouse** [comment]
closing this now - as node 0.10.x is old, I am using node  4.x

root@csx00407 test]# npm install -g loopback-connector-oracle --unsafe-perm
/
> loopback-oracle-installer@3.0.0 install /opt/ibm/node4/lib/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

Installation values -> oracledb location: /opt/ibm/node4/lib/node_modules/loopback-connector-oracle/node_modules Prepackaged tarball url: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com  oracleversion: 2.0.0 oracledbmodule: oracledb@^1.11.0

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi46-2.0.0.tar.gz

http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi46-2.0.0.tar.gz is now extracted to /opt/ibm/node4/lib/node_modules/loopback-connector-oracle/node_modules
Oracle instant client is installed to /root/oracle-instant-client
loopback-connector-oracle@3.0.0 /opt/ibm/node4/lib/node_modules/loopback-connector-oracle
├── async@1.5.2
├── debug@2.6.0 (ms@0.7.2)
├── loopback-connector@2.7.1 (bluebird@3.4.7, msgpack5@3.4.1)
├── strong-globalize@2.8.0 (optional@0.1.3, estraverse@4.2.0, word-count@0.2.2, posix-getopt@1.2.0, xtend@4.0.1, esprima@2.7.3, md5@2.2.1, mktmpdir@0.1.1, os-locale@1.4.0, mkdirp@0.5.1, htmlparser2@3.9.2, fs-sync@1.0.3, yamljs@0.2.8, g11n-pipeline@1.3.0, lodash@4.17.4)
└── loopback-oracle-installer@3.0.0 (os-homedir@1.0.2, graceful-fs@4.1.11, tar@1.0.3, cross-spawn@4.0.2, fs-extra@0.30.0, fstream@1.0.10, buffered-stream@0.0.1, request@2.79.0)
[root@csx00407 test]# 

[root@csx00407 test]# node -v
v4.4.5
 it is working now on RHEL 7.x
