### ISSUE TITLE
Unable to Discover Oracle Models using ARC Composer

### ISSUE THREAD

**Issue by aellison9** [strongloop/loopback-connector-oracle#55]
When attempting to discover models using slc arc and the oracle connector, the cursor on the window spins for about 2 minutes and then returns an empty list instead of a populated table list.

The connection within composer tests successfully for both the Oracle datasource and the Postgresql datasource. Discover models works successfully for the Postgresql datasource but not the Oracle datasource.

This might very well be an ARC Composer issue, but starting here since it only manifests when trying to use the oracle connector.

Steps to reproduce:
1) create a new loopback project using 
$ slc loopback connectortest
2) cd connectortest
3) npm install --save loopback-connector-postgresql
4) npm install --save loopback-connector-oracle
complete the oracle connector installation
5) cd node_modules/loopback-connector-oracle
6) npm install
7) change directory back to project home directory
8) slc arc
9) login to ARC console and navigate to composer
10) add datasource for both oracle and postgresql
11) try to discover models

Additional info: I can discover the Oracle models successfully by invoking the API call directly. Test javascript attached.

[test_oracle_discovery_script.txt](https://github.com/strongloop/loopback-connector-oracle/files/81839/test_oracle_discovery_script.txt)
[test_oracle_discovery_output.txt](https://github.com/strongloop/loopback-connector-oracle/files/81840/test_oracle_discovery_output.txt)
![screen shot 2016-01-07 at 4 08 15 pm](https://cloud.githubusercontent.com/assets/15879237/12184421/bf41c5e2-b55a-11e5-8780-3d8724dc65a6.png)
![screen shot 2016-01-07 at 4 12 32 pm](https://cloud.githubusercontent.com/assets/15879237/12184425/c45743cc-b55a-11e5-93f6-6ad7248bbe8a.png)

ENVIRONMENT INFO:

OS X Yosemite version 10.10.5
node v5.4.0
strongloop v6.0.0 (node v5.4.0)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

loopback-connector-postgresql@2.4.0
loopback-connector-oracle@2.3.0

**Comment by anoop-ananthan** [comment]
Is strongloop still alive?
