### ISSUE TITLE
cannot install connector

### ISSUE THREAD

**Issue by cristtopher** [strongloop/loopback-connector-oracle#59]
`$ npm install loopback-connector-oracle --save`

npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN mefapi@1.0.0 No license field.

`$ node .`

WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

**Comment by jannyHou** [comment]
@cristtopher which system are you using?
For oracle connector, we need some other config to get it work:
Please check our doc for installation: 
https://docs.strongloop.com/display/public/LB/Installing+the+Oracle+connector

BTW, if you are using linux system or mac, please follow the instruction and export LD_LIBRARY_PATH:
`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/Users/<user>/<myapp>/node_modules/loopback-connector-oracle/node_modules/instantclient"`

**Comment by tmannian** [comment]
I seem to be experiencing the same error.  O/S Windows 7, Node 4.4.3, npm 3.8.6. Attempt to install into project and am met with a failure telling me something is likely wrong with the loopback-oracle install package.


[npm-debug.txt](https://github.com/strongloop/loopback-connector-oracle/files/226439/npm-debug.txt)

**Comment by eholzwarth** [comment]
Same issue, and yes I followed the instructions for updating LD_LIBRARY_PATH. RHEL 7 Node 4.4.2.

**Comment by BiteBit** [comment]
Same issue, and yes I followed the instructions for updating LD_LIBRARY_PATH. RHEL 7 Node 4.4.2.

**Comment by jannyHou** [comment]
@BiteBit @eholzwarth Did you try the following **TWO** steps?
> "strong-oracle.rc" has been created in $HOME. Please manually add the
following to your ".bash_profile":
  source /Users/jannyhou/strong-oracle.rc
If you do not use bash as your default shell, please remember to set
$DYLD_LIBRARY_PATH prior to using node:
  export DYLD_LIBRARY_PATH=":/Users/jannyhou/lb/triage/loopback-test/node_modules/instantclient"

When you install loopback-connector-oracle, those steps will be printed on your console.

And we have a new version of oracle connector which doesn't need config, but it's not published yet. I will also update it here as long as it's released.

**Comment by BiteBit** [comment]
@jannyHou Yes,  I already tried that. 
Now, i download the source code of strong-oracle and build by manual. I'm success.
I guess  my library path is wrong, i already install instantclient 12 before.

**Comment by cjbj** [comment]
Is this with node-oracledb?  On Linux you could set FORCE_RPATH=1 in the shell installing node-oracledb.  You would no longer need to set LD_LIBRARY_PATH at runtime.  This may not work if you are moving binaries around e.g. between machines with different install locations.

See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#linuxadv

**Comment by jannyHou** [comment]
I am closing this issue due to out of date, and I believe the installation problem is already fixed. I am able to run test several times on local. Thanks for understanding.
