### ISSUE TITLE
Fail to loopback-connector-oracle on Windows 10

### ISSUE THREAD

**Issue by yueyuezhou** [strongloop/loopback-connector-oracle#60]
C:\Users\yuzhou\Documents\nodejs\test1>npm install --save loopback-connector-ora
cle
npm WARN package.json test1@1.0.0 No README data
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> loopback-oracle-installer@1.4.2 install C:\Users\yuzhou\Documents\nodejs\test1
> \node_modules\loopback-connector-oracle\node_modules\loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f575
1b6.r22.cf1.rackcdn.com/loopback-oracle-Windows-x64-abi46-1.8.0.tar.gz
HTTP proxy: http://www-proxy.us.oracle.com:80/
[Error: Prebuilt tarball not found for your node version and platform: http://7e
9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback
-oracle-Windows-x64-abi46-1.8.0.tar.gz]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "--save" "loopback-connector-oracl
e"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@1.4.2 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@1.4.2 install script 'node pkgi
nstall.js'.
npm ERR! This is most likely a problem with the loopback-oracle-installer packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs loopback-oracle-installer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\yuzhou\Documents\nodejs\test1\npm-debug.log

**Comment by raymondfeng** [comment]
We don’t have a prebuilt binary for Node 4.4.0 on Windows 64 bit.

Can you try Node 5.x?

**Comment by yueyuezhou** [comment]
Node 5.91 solve the issue above. 

However, I don't have in instantclient under C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loopback-connector-oracle\node_modules. And PATH remains the same.

When I tried to start the server, I got the following error message:

C:\Users\yuzhou\Documents\nodejs\edge1>node .

WARNING: LoopBack connector "oracle" is not installed as any of the following mo
dules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error:
WARNING: LoopBack connector "oracle" is not installed as any of the following mo
dules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

    at DataSource.setup (C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loo
pback-datasource-juggler\lib\datasource.js:304:28)
    at new DataSource (C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loopb
ack-datasource-juggler\lib\datasource.js:109:8)
    at Registry.createDataSource (C:\Users\yuzhou\Documents\nodejs\edge1\node_mo
dules\loopback\lib\registry.js:349:12)
    at dataSourcesFromConfig (C:\Users\yuzhou\Documents\nodejs\edge1\node_module
s\loopback\lib\application.js:415:19)
    at EventEmitter.app.dataSource (C:\Users\yuzhou\Documents\nodejs\edge1\node_
modules\loopback\lib\application.js:222:12)
    at C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loopback-boot\lib\exe
cutor.js:174:9
    at C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loopback-boot\lib\exe
cutor.js:265:5
    at Array.forEach (native)
    at forEachKeyedObject (C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\l
oopback-boot\lib\executor.js:264:20)
    at setupDataSources (C:\Users\yuzhou\Documents\nodejs\edge1\node_modules\loo
pback-boot\lib\executor.js:173:3)

**Comment by yueyuezhou** [comment]
![image](https://cloud.githubusercontent.com/assets/1118021/14005286/74b8dc00-f127-11e5-93c7-d04295cf4a18.png)

**Comment by yueyuezhou** [comment]
Why does it try to download the file from local?

**Comment by yueyuezhou** [comment]
switched to a linux box, and was able to install loopback-connector-oracle. but failed to connect a remote database.

Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

I have no Oracle client installed but the instant driver. Is there anyway to test/debug the issue? Thanks

**Comment by emulicus** [comment]
Is there a list somewhere where we can get the the list of generated node/os combinations?
I'm getting the same error, I have Windows 7 64 bit + Node 6.7.0.

**Comment by superkhau** [comment]
@crandmck Do you think you can compile a list of combinations in the docs somewhere (if we don't have one already)?

**Comment by crandmck** [comment]
I don't think I'm the right person to compile this list.  I'm happy to add it to the docs once we have the info.  

It should probably be based on what we test.  Can someone in QA provide the list of tested OS / Node versions that we test this connector on?  
@0candy @cgole

**Comment by renanwilliam** [comment]
how we can compile this connector to make available to other versions?

**Comment by crandmck** [comment]
@0candy Could you please find someone who can provide the info based on Node/OS combos on which we test this connector?  Then reassign to me...thanks!

**Comment by 0candy** [comment]
@cgole Do you have the info that @crandmck is looking for?

**Comment by kjdelisle** [comment]
pinging @cgole, see above.
