### ISSUE TITLE
Switch to the official Oracle driver

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-oracle#61]
- finish the work

**Comment by jannyHou** [comment]
@ssh24 @laven26 Please verify the refactored loopback-connector-oracle works fine. 

**Verify Steps:**

Probably make sure the installation and connection work first:
[1] create a lb app: `slc loopback`
[2] install loopback-connector-oracle from staging registry(with the latest commit)
[3] create a oracle datasource: `slc loopback:datasource`
[4] should work without additional config
[5] create a model attach to oracle ds
[6] try endpoint in explorer and make sure CRUD operations work fine.

**Comment by ssh24** [comment]
`Verified with npm version:` **3.9.5**

1. Set registry to staging: `npm config set registry http://ci.strongloop.com:4873/`
2. Install the latest strongloop: `npm install -g strongloop`
3. Create a lb app: `slc loopback --name APP_NAME`
4. Install the loopback-connector for oracle: `npm install loopback-connector-oracle --save`
5. Create a datasource with valid credentials: `slc loopback:datasource`
6. Create a model and attach the datasource in 4. to it: `slc loopback:model`
7. CRUD methods `GET, POST, PUT` works as expected

**Comment by cjbj** [comment]
Make sure to use oracledb 1.9.3 (the current latest)

**Comment by dhmlau** [comment]
@bajtos, seems like the work is done.  Is it good to close?  Thanks.

**Comment by bajtos** [comment]
Sure, let's close. We should open new issue(s) if there is anything missing.
