### ISSUE TITLE
Improve installation experience

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-oracle#62]
Find better ways how to configure the path to instant client dynamic library, so that we don't have to mess with ENV variables.

**Comment by bajtos** [comment]
Once we decide what needs to be done and make the changes, then we should cut a new major release and write a mini-announcement (blog post?)

**Comment by bajtos** [comment]
We should probably get QA to test the new version before publishing to npmjs.org

**Comment by raymondfeng** [comment]
Connect to strongloop/loopback-oracle-builder#3
Connect to strongloop/loopback-oracle-installer#11

**Comment by ebickle** [comment]
Would it be possible to remove the dependency that loopback-connector-oracle takes on loopbac-oracle-installer? 

The proper installation of the oracledb driver (node-oracle) is a concern of that NPM module and not something inherently required for the Loopback Oracle connector. We're binding against the loopback-oracle-connector master branch (3.0.0) to get full oracledb support, 

Even when my machine is configured to successfully build the oracledb package using 'npm install oracledb' on Windows 7/x64/Visual Studio 2015 Professional, an 'npm install loopback-connector-oracle' picks up the dependency on loopback-oracle-installer and fails at node pkginstall.js with an irrecoverable failure. Even worse, it's downloading precompiled database driver binaries from (in our Enterprise's view) an untrusted and unverifiable location (*.rackcdn.com).

I can definitely see the value in making it easy to install and compile oracledb, but it would be a lot easier if that "helper" wasn't part of the requirements chain - it should be optional. Right now we're forced to take an npm dependency against a private fork of loopback-connector-oracle to resolve the issue.

**Comment by bajtos** [comment]
@rashmihunt @raymondfeng PTAL ☝️
