### ISSUE TITLE
Meet ORA-03134 error when connect to an oracle 10g server on Ubuntu 14.04

### ISSUE THREAD

**Issue by wzsh** [strongloop/loopback-connector-oracle#71]
when i deploy my api service to an ubuntu 14.04 server and try to connect to an oracle 10g server by this connector, it caused the error as following:
`ORA-03134: Connections to this server version are no longer supported.`

The reason is when i run `npm install loopback-connector-oracle`, the loopback-oracle-installer installed the oracle instantsclient 12_1 as default, and oracle documents show that 12_1 client no longer supports the 10g server and below.

I wonder if i can use oracle client 11_2 as the connector. i had tried to dowload and setup the instantsclient11_2 manually by following the instruction of Strong-Oracle, but it shows no 'oracle' connector installed. is there any way that i can connect to the oracle 10g server on ubuntu?

**Comment by dmpstaltari** [comment]
Hi, i have the same problem (Windows 10 Pro and Oracle 9i - 9.2.0.5.0), could you solve it?

**Comment by raymondfeng** [comment]
You probably need to use Oracle instant client 11.x to access 10g. The 3.x version of loopback-connector-oracle uses `oracledb` as the driver. Please see https://github.com/oracle/node-oracledb/blob/master/INSTALL.md.

I assume you can download oracle instant client 11.x and configure OCI_LIB_DIR & OCI_INC_DIR.

**Comment by dmpstaltari** [comment]
Hi Raymond,
I did all the steps of the post and can run the example without problems, but when using Loopback I have a new error "Error: DPI-007: invalid OCI handle or descriptor at Error (native)"

Do you have any idea how to solve this problem?

Thanks in advance!

OS: Windows 10 Pro
Node: 6.9.5
Oracle Instant client: 11.2.0.2.0
Oracle DB: Oracle9i Enterprise Edition Release 9.2.0.5.0
loopback-connector-oracle: 3.0.0

**Comment by xavit** [comment]
I have the same problem on Windows 8, I tried to install Oracle instant client 11.x becouse I need to connect loopback with Oracle 9i and 10g and not sure what Instant client version to use.
Thanks in advance!

**Comment by cjbj** [comment]
@dmpstaltari  See https://github.com/oracle/node-oracledb/issues/625
Fundamentally 9i is so old, it's not funny.

**Comment by cjbj** [comment]
@dmpstaltari @xavit the workaround to the DPI-007 error when using a connection pool to a 9i database is to disable connection pinging by setting `oracledb.poolPingInterval = -1`  See (https://github.com/oracle/node-oracledb/issues/625)
