### ISSUE TITLE
loopback-oracle-installer@1.4.6 Installation failing

### ISSUE THREAD

**Issue by ashishthcl** [strongloop/loopback-connector-oracle#75]
Hi, 

I am getting following error while running 

`npm install loopback-connector-oracle --save` in Windows 7 64 bit.

I encountered this error few hours before. Earlier, I was not getting any exception during installation.  I also tried to clear cache at `C:\Users\atiw26\AppData\Roaming\npm-cache` and fired the same installation command. But still getting this error.

I had to reinstall this package because of another error during the execution of sample for Oracle Connectors.

[npm-debug.zip](https://github.com/strongloop/loopback-connector-oracle/files/441026/npm-debug.zip)

I am attaching the logs which are generated during the Oracle Connector installation.

**Comment by jannyHou** [comment]
@ashishthcl Thank you for reporting the problem. I believe it's the same issue as https://github.com/strongloop/loopback-connector-oracle/issues/59#issuecomment-212023899

Closing this one as a duplicate and let't follow up the fix in the existing one.
