### ISSUE TITLE
Finalize Oracle connector installation experience

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-oracle#79]
1. What installation experience do we want? Are manual steps acceptable?
   1. Implement the scheme based on the answers to 1)
   2. Release the new updated connector

**Comment by bajtos** [comment]
Timeboxed to 5 story points for Sprint 21

**Comment by rashmihunt** [comment]
Oracle connector changes:

-  When pre-packaged tarball is not found during  oracle connector installation,  installer needs to print out a message to install oracle pre-requisites offline and re-install conenctor again.

- Once user has installed oracle pre-requisites offline and re-run to install oracle connector again, the installation should go through successfully and install 'Oracledb' node module under loopback-connector-oracle.

**Comment by raymondfeng** [comment]
More thoughts to further optimize the installation experience.

1. Make Oracle Instant Clients available on CDN and remove corresponding files from the driver bundle. Update the installer to download/install Oracle Instant Client separately before installing the driver.

2. Explore `rpath` for Mac and Linux platforms to remove needs to set env vars

3. For Windows, append Oracle Instant Client dir to `PATH` in code before `require('oracledb')`.

**Comment by rashmihunt** [comment]
@raymondfend I have opened 2nd set of improvement here https://github.com/strongloop-internal/scrum-loopback/issues/1180
We should merge current PRs as customer will benefit from the improvement we have done so far where they will not be blocked by not installing oracle connector if pre-packaged tarball doesn't exist on remote site.
