### ISSUE TITLE
Unable to install Loop Back Oracle Module.

### ISSUE THREAD

**Issue by telkomops** [strongloop/loopback-connector-oracle#89]
Trying to install Loopback oracle module on Windows 8.1 x64 Box.
Facing an error.
Error: Prebuilt tarball not found for your node version and platform: http://7e
918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback
oracle-Windows-x64-abi48-1.8.0.tar.gz

Is there a way to resolve this issue.
node.js version is v6.2.2
npm version is 3.9.5

Trying to install Strong-Oracle directly fails with Windows 8.1 SDK missing. I donot want to pursue this option.
Any pointers? c:\oracle\instantclient is present in the path

**Comment by dhmlau** [comment]
@telkomops , sorry to take so long to respond.  If possible, I'd recommend to try again with the latest version of the oracle connector, i.e. `3.x`.  The installation and configuration of `node-oracledb` is simpler in 3.x.  For details, please refer to the [Installation section of `README.md`](https://github.com/strongloop/loopback-connector-oracle#installation).

**Comment by dhmlau** [comment]
Closing this issue.  Please see the response above.  Feel free to reopen this issue if it's not resolved.
