### ISSUE TITLE
Publish version 3.0.0 to NPM

### ISSUE THREAD

**Issue by ebickle** [strongloop/loopback-connector-oracle#90]
The latest changes in /master to support a direct dependency against the official Oracle driver (node-oracledb) aren't published to NPM as an alpha version yet.

Would it be possible to branch loopback-connector-oracle to a 3.x-latest" branch and then publish it as a pre-release alpha version to npm? The last non-documentation and non-globalization checkin was back in May. 

We'd like to use the 3.x form of loopback-connector-oracle shortly after Loopback 3 when it's released - how stable is the new connector, and what's needed to get it complete?

**Comment by dhmlau** [comment]
@ebickle, the current version of `loopback-connector-oracle` is now 3.1.1.  Closing this..
