### ISSUE TITLE
Type Coercion for String to RAW

### ISSUE THREAD

**Issue by ebickle** [strongloop/loopback-connector-oracle#91]
Loopback-connector-oracle 3.0 (master) has partial support for RAW data types; if a loopback property is set with the type "string" and contains hexadecimal, the Oracle database engine will coerce it to RAW.

However, this conversion occurs after the queryplan is established - comparing an indexed RAW column to a hexadecimal string (such as a UUID) will cause a table scan - no indexes are ever used. The proper Oracle workaround is to place "hextoraw" in the query so that Oracle's queryplan is correctly comparing raw to raw. 

What I propose is that the loopback-oracle-connector toColumnValue function look at the oracle.dataType parameter to determine whether we are coercing to RAW and then wrap the argument in the hextoraw function. We use RAW(16) UUIDs as our primary keys - we are seeing 3000ms+ queries in loopback by default, with < 20ms once we manually made this change. 

The change is simple - in oracle.js of loopback-connector-oracle, change the "if (prop.type == String)" to something similar to this:
```
  if (prop.type === String) {
    if (prop.oracle && prop.oracle.dataType === "RAW") {
      return new ParameterizedSQL("hextoraw(?)", [val]);
    }

    return String(val);
  }
```

I'm willing to submit a pull request, but I believe your unit tests only run in Mac/Linux.

**Comment by raymondfeng** [comment]
+1

**Comment by superkhau** [comment]
@ebickle Would you like to submit a PR?
