### ISSUE TITLE
Ci failures for node 4.6/6.x on windows, x64, linux

### ISSUE THREAD

**Issue by siddhipai** [strongloop/loopback-connector-oracle#98]
see [#97](https://github.com/strongloop/loopback-connector-oracle/pull/97)

**Comment by loay** [comment]
Issue is fixed. 
There was one last failure on linux and it is fixed as per this pr: https://github.com/strongloop/loopback-datasource-juggler/pull/1265

Please re-open if you still encounter the issue. Thanks.
